import {
  billingSource,
  legacyFailoverCorpusRows,
} from "./failover-classification.corpus.test-support.js";

// Distinct real inputs preserved from matcher-specific suites retired by refactor-02.
export const legacyBillingBCases = legacyFailoverCorpusRows("legacy-billing-b", billingSource, [
  [1, "classifyFailoverReason", "HTTP 422: insufficient credits", "billing"],
  [2, "classifyFailoverReason", "HTTP 422: No body", null],
  [3, "classifyFailoverReason", "HTTP 422: No response body", null],
  [4, "classifyFailoverReason", "HTTP 422: Unprocessable Entity", "format"],
  [5, "classifyFailoverReason", "HTTP 499", "timeout"],
  [
    6,
    "classifyFailoverReason",
    'HTTP 499: {"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}',
    "overloaded",
  ],
  [7, "classifyFailoverReason", "HTTP 499: 499 Client Closed Request", "timeout"],
  [8, "classifyFailoverReason", "HTTP 500", "timeout"],
  [
    9,
    "classifyFailoverReason",
    'HTTP 500: Codex error: {"type":"error","error":{"type":"server_error","code":"server_error","message":"An error occurred while processing your request."},"sequence_number":2}',
    "server_error",
  ],
  [
    10,
    "classifyFailoverReason",
    'HTTP 502: Codex error: {"type":"error","error":{"type":"server_error","code":"server_error","message":"An error occurred while processing your request."},"sequence_number":2}',
    "server_error",
  ],
  [
    11,
    "classifyFailoverReason",
    'HTTP 504: Codex error: {"type":"error","error":{"type":"server_error","code":"server_error","message":"An error occurred while processing your request."},"sequence_number":2}',
    "server_error",
  ],
  [
    12,
    "isBillingErrorMessage,isLikelyContextOverflowError",
    "insufficient credits: request size exceeds your current plan limits",
    "billing",
  ],
  [
    13,
    "isBillingErrorMessage,isFailoverErrorMessage,classifyFailoverReason; src/agents/embedded-agent-helpers/provider-error-patterns.test.ts#matchesProviderContextOverflow",
    "invalid api key",
    "auth",
  ],
  [14, "isAuthPermanentErrorMessage", "invalid token", "auth"],
  [15, "isBillingErrorMessage", "ISSUE-402 has been resolved", null],
  [16, "isAuthPermanentErrorMessage", "key has been revoked", "auth_permanent"],
  [18, "isContextOverflowError", "Let's investigate the context overflow bug", null],
  [19, "classifyFailoverReason", "LLM request failed with an unknown error.", null],
  [
    20,
    "classifyFailoverReason",
    "LLM request rejected: does not support assistant message prefill",
    "format",
  ],
  [
    21,
    "classifyFailoverReason",
    "messages.84.content.1.image.source.base64.data: At least one of the image dimensions exceed max allowed size for many-image requests: 2000 pixels",
    null,
  ],
  [
    22,
    "isLikelyContextOverflowError",
    "Model context window too small (minimum is 128k tokens)",
    null,
  ],
  [23, "isContextOverflowError", "model not found", "model_not_found"],
  [24, "isContextOverflowError", "model_context_window_exceeded", "context_overflow"],
  [25, "classifyFailoverReason", "no api key found", "auth"],
  [
    26,
    "classifyFailoverReason",
    'No API key found for provider "openai". Auth store: /tmp/openclaw-agent-abc/auth-profiles.json (agentDir: /tmp/openclaw-agent-abc).',
    "auth",
  ],
  [27, "classifyFailoverReason", "no credentials found", "auth"],
  [
    28,
    "classifyFailoverReason",
    "OAuth token refresh failed for openai: file lock timeout for /tmp/agent/auth-profiles.json. Please try again or re-authenticate.",
    "auth",
    "openai",
  ],
  [
    29,
    "classifyFailoverReason",
    "OAuth token refresh failed for openai: invalid_grant. Please try again or re-authenticate.",
    "auth_permanent",
    "openai",
  ],
  [30, "isBillingErrorMessage", "Payment Required", "billing"],
  [31, "isBillingErrorMessage", "port 402 is open", null],
  [32, "isBillingErrorMessage", "processed 402 records", null],
  [33, "classifyFailoverReason", "Prompt is too long", "context_overflow"],
  [
    34,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage; src/agents/embedded-agent-helpers/failover-matches.test.ts#isServerErrorMessage",
    "Proxy notice: Status: Internal Server Error",
    null,
  ],
  [
    35,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "Proxy notice: Status: Internal Server Error; code:500",
    "timeout",
  ],
  [
    36,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "Proxy notice: Status: Internal Server Error; upstream connect error",
    "timeout",
  ],
  [
    37,
    "isBillingErrorMessage",
    "Quarterly report summary: subsystem A returned 402 records after retry. This is an analytics count, not an HTTP/API billing failure. Notes: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "billing",
  ],
  [
    38,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "reason: abort",
    "timeout",
  ],
  [
    39,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "reason: network_error",
    "timeout",
  ],
  [40, "isBillingErrorMessage", "received a 402 response", "billing"],
  [
    41,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "request failed",
    "timeout",
  ],
  [42, "isContextOverflowError", "request size exceeds model context window", "context_overflow"],
  [43, "isContextOverflowError", "request size exceeds upload limit", null],
  [44, "isFailoverErrorMessage", "request timed out", "timeout"],
  [45, "isBillingErrorMessage", "Room 402 is available", null],
  [46, "isBillingErrorMessage", "See ticket #402 for details", null],
  [47, "isContextOverflowError", "Something is causing context overflow messages", null],
  [48, "isBillingErrorMessage", "status=402 payment required", "billing"],
  [
    49,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "stop reason: abort",
    "timeout",
  ],
  [
    50,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "stop reason: error",
    "server_error",
  ],
  [
    51,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "stop reason: MALFORMED_RESPONSE",
    "timeout",
  ],
  [
    52,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "stop reason: network_error",
    "timeout",
  ],
  [
    53,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "stream aborted",
    "timeout",
  ],
  [
    54,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "stream closed",
    "timeout",
  ],
  [
    55,
    "isBillingErrorMessage",
    "Sure! Here's how to set up billing for your SaaS application.\n\n## Payment Integration\n\nFirst, you'll need to configure your payment gateway. Most providers offer a dashboard where you can manage credits, view invoices, and upgrade your plan. The billing page typically shows your current balance and payment history.\n\n## Managing Credits\n\nUsers can purchase credits through the billing portal. When their credit balance runs low, send them a notification to upgrade their plan or add more credits. You should also handle insufficient balance cases gracefully.\n\n## Subscription Plans\n\nOffer multiple plan tiers with different features. Allow users to upgrade or downgrade their plan at any time. Make sure the billing cycle is clear.\n\nLet me know if you need more details on any of these topics!",
    null,
  ],
  [
    56,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "Terminated",
    "timeout",
  ],
  [57, "isBillingErrorMessage", "The building at 402 Main Street", null],
  [
    58,
    "isBillingErrorMessage,classifyFailoverReason",
    "The evidence is insufficient to reconcile the final balance after compaction.",
    null,
  ],
  [59, "isContextOverflowError", "The mystery context overflow errors are strange", null],
  [
    60,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "the operation was aborted",
    "timeout",
  ],
  [
    61,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "The user terminated the session manually.",
    null,
  ],
  [62, "isBillingErrorMessage", "There is a 402 near me", null],
  [63, "isLikelyContextOverflowError", "This endpoint requires reasoning", null],
  [64, "isContextOverflowError", "This model requires reasoning to be enabled", null],
  [
    65,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "This operation was aborted",
    "timeout",
  ],
  [66, "isAuthPermanentErrorMessage", "token has expired", "auth"],
  [67, "isAuthPermanentErrorMessage", "unauthorized", "auth"],
  [
    68,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "UND_ERR_SOCKET",
    "timeout",
  ],
  [
    69,
    "isContextOverflowError",
    "Unhandled stop reason: context_window_exceeded",
    "context_overflow",
  ],
  [
    70,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "Unhandled stop reason: error",
    "server_error",
  ],
  [
    71,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "Unhandled stop reason: malformed_response",
    "timeout",
  ],
  [
    72,
    "classifyFailoverReason,isFailoverErrorMessage",
    "Unknown error (no error details in response)",
    "no_error_details",
  ],
  [73, "isBillingErrorMessage", "Use a 402 stainless bolt", null],
  [74, "classifyFailoverReason", "user reported that an unknown error occurred during sync", null],
  [75, "isContextOverflowError", "We're debugging context overflow issues", null],
  [
    76,
    "classifyFailoverReason",
    "You've hit your usage limit. Upgrade to Plus to continue using Codex (https://chatgpt.com/explore/plus), try again after 11:34 AM.",
    "rate_limit",
    "openai",
  ],
  [
    77,
    "classifyFailoverReason",
    "You've hit your usage limit. Visit https://chatgpt.com/codex/settings/usage to purchase more credits, try again later.",
    "rate_limit",
    "openai",
  ],
  [
    78,
    "classifyFailoverReason",
    "Your access token could not be refreshed because you have since logged out or signed in to another account. Please sign in again.",
    "auth_permanent",
    "openai",
  ],
  [
    79,
    "classifyFailoverReason",
    "Your authentication session could not be refreshed automatically. Please log out and sign in again.",
    "auth_permanent",
    "openai",
  ],
  [80, "isFailoverErrorMessage", "Your credit balance is too low", "billing"],
  [
    81,
    "isBillingErrorMessage,isLikelyContextOverflowError",
    "Your credit balance is too low. Maximum request token limit exceeded.",
    "billing",
  ],
  [82, "isContextOverflowError", "上下文过长", "context_overflow"],
]);
