import {
  billingSource,
  legacyFailoverCorpusRows,
} from "./failover-classification.corpus.test-support.js";

// Distinct real inputs preserved from matcher-specific suites retired by refactor-02.
export const legacyBillingACases = legacyFailoverCorpusRows("legacy-billing-a", billingSource, [
  [1, "classifyFailoverReason,isFailoverErrorMessage", "  An unknown error occurred  ", "timeout"],
  [
    2,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "  Request failed  ",
    "timeout",
  ],
  [
    3,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "  stream_read_error  ",
    "timeout",
  ],
  [
    4,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "  terminated  ",
    "timeout",
  ],
  [
    5,
    "isBillingErrorMessage",
    '{"error":{"code":402,"message":"payment required","details":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}}',
    "billing",
  ],
  [
    6,
    "classifyFailoverReason",
    '{"type":"error","error":{"type":"api_error","message":"invalid input format"}}',
    null,
  ],
  [
    7,
    "classifyFailoverReason",
    '{"type":"error","error":{"type":"api_error","message":"messages.1.content.1.tool_use.id should match pattern"}}',
    "format",
  ],
  [
    8,
    "classifyFailoverReason",
    '{"type":"error","error":{"type":"api_error","message":"Request size exceeds model context window"}}',
    "context_overflow",
  ],
  [
    9,
    "isContextOverflowError,isLikelyContextOverflowError",
    '{"type":"error","error":{"type":"invalid_request_error","message":"Reasoning is mandatory for this endpoint and cannot be disabled."}}',
    "format",
  ],
  [10, "isBillingErrorMessage,classifyFailoverReason", "402 items found in the database", null],
  [
    11,
    "classifyFailoverReason",
    '402 Payment Required Codex error: {"type":"error","error":{"type":"server_error","code":"server_error","message":"An error occurred while processing your request."},"sequence_number":2}',
    "billing",
  ],
  [
    12,
    "isBillingErrorMessage,isLikelyContextOverflowError",
    "402 Payment Required: request token limit exceeded for this billing plan",
    "billing",
  ],
  [13, "classifyFailoverReason", "402 records processed", null],
  [14, "classifyFailoverReason", "402 room is available", null],
  [15, "classifyFailoverReason", "404 status code (no body)", "model_not_found"],
  [16, "classifyFailoverReason", "410", "timeout"],
  [17, "classifyFailoverReason", "410 conversation expired", "session_expired"],
  [18, "classifyFailoverReason", "410 Gone", "timeout"],
  [19, "classifyFailoverReason", "410: No body", "timeout"],
  [20, "classifyFailoverReason", "422 status code (no body)", null],
  [
    21,
    "classifyFailoverReason",
    '429 {"type":"error","error":{"type":"rate_limit_error","message":"You\\u0027ve hit your usage limit. Upgrade to Plus to continue using Codex (https://chatgpt.com/explore/plus), try again after 11:34 AM."}}',
    "rate_limit",
    "openai",
  ],
  [22, "isFailoverErrorMessage", "429 rate limit exceeded", "rate_limit"],
  [23, "isAuthPermanentErrorMessage", "access denied", "auth"],
  [24, "classifyFailoverReason", "all credentials for model x are cooling down", null],
  [25, "classifyFailoverReason,isFailoverErrorMessage", "an unknown error occurred", "timeout"],
  [26, "classifyFailoverReason,isFailoverErrorMessage", "AN UNKNOWN ERROR OCCURRED", "timeout"],
  [27, "classifyFailoverReason,isFailoverErrorMessage", "An unknown error occurred.", "timeout"],
  [28, "isAuthPermanentErrorMessage", "api key deactivated", "auth_permanent"],
  [29, "isAuthPermanentErrorMessage", "api key revoked", "auth_permanent"],
  [30, "isAuthPermanentErrorMessage", "api_key_deleted", "auth_permanent"],
  [31, "isAuthPermanentErrorMessage", "API_KEY_REVOKED", "auth_permanent"],
  [32, "isAuthPermanentErrorMessage,isContextOverflowError", "authentication failed", "auth"],
  [33, "classifyFailoverReason", "bad request", null],
  [34, "isAuthErrorMessage", "billing issue detected", null],
  [35, "isBillingErrorMessage", "Book a 402 room", null],
  [
    36,
    "isLikelyContextOverflowError,classifyFailoverReason",
    "Context window exceeded: too many tokens per request.",
    null,
  ],
  [37, "isLikelyContextOverflowError", "Context window too small: minimum is 1000 tokens", null],
  [38, "classifyFailoverReason", "conversation must end with a user message", "format"],
  [39, "isAuthPermanentErrorMessage", "deactivated workspace", "auth_permanent"],
  [40, "isAuthPermanentErrorMessage", "deactivated_workspace", "auth_permanent"],
  [41, "isBillingErrorMessage", "Error code 403 was returned, not 402-related", "auth"],
  [
    42,
    "classifyFailoverReason",
    'ERROR provider=google model=gemini-3.1-flash-lite-preview: got status: INTERNAL, details: {"code":500,"status":"INTERNAL"}',
    "timeout",
  ],
  [43, "classifyFailoverReason", "Error: HTTP 422: No response body", null],
  [44, "isLikelyContextOverflowError", "exceeded your current quota", "rate_limit"],
  [
    45,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    "finish_reason: error",
    "server_error",
  ],
  [46, "isBillingErrorMessage", "Fixed issue CHE-402 in the latest release", null],
  [47, "isAuthPermanentErrorMessage", "forbidden", "auth"],
  [48, "isBillingErrorMessage", "got a 402 from the API", "billing"],
  [
    49,
    "isTimeoutErrorMessage,classifyFailoverReason,isFailoverErrorMessage",
    'got status: INTERNAL. {"error":{"code":400,"message":"Request malformed","status":"INTERNAL"}}',
    null,
  ],
  [
    50,
    "classifyFailoverReason",
    'got status: INTERNAL. {"error":{"code":500,"message":"Internal error encountered.","status":"INTERNAL"}}',
    "timeout",
  ],
  [
    51,
    "classifyFailoverReason",
    'HTTP 400: {"type":"error","error":{"type":"insufficient_quota","message":"Your account has insufficient quota balance to run this request."}}',
    "billing",
  ],
  [
    52,
    "classifyFailoverReason",
    "HTTP 400: INVALID_ARGUMENT: input exceeds the maximum number of tokens",
    "context_overflow",
  ],
  [53, "classifyFailoverReason", "HTTP 400: No body", null],
  [
    54,
    "classifyFailoverReason",
    "HTTP 400: ThrottlingException: Too many concurrent requests",
    "rate_limit",
  ],
  [
    55,
    "classifyFailoverReason",
    'HTTP 401: {"type":"error","error":{"type":"server_error","code":"server_error"}}',
    "auth",
  ],
  [57, "isBillingErrorMessage", "http 402", "billing"],
  [58, "classifyFailoverReason", "HTTP 402", "billing"],
  [
    59,
    "classifyFailoverReason",
    'HTTP 402: {"type":"error","error":{"type":"server_error","code":"server_error"}}',
    "billing",
  ],
  [60, "classifyFailoverReason", "HTTP 402: 402: rate limit exceeded", "rate_limit"],
  [61, "classifyFailoverReason", "HTTP 402: Daily limit reached, resets tomorrow.", "rate_limit"],
  [
    62,
    "classifyFailoverReason",
    "HTTP 402: Insufficient credits. Organization limit reached.",
    "billing",
  ],
  [
    63,
    "classifyFailoverReason",
    "HTTP 402: Monthly spend limit reached. Please visit your billing settings.",
    "rate_limit",
  ],
  [64, "classifyFailoverReason", "HTTP 402: Payment required", "billing"],
  [65, "classifyFailoverReason", "HTTP 402: rate limit exceeded", "rate_limit"],
  [
    66,
    "classifyFailoverReason",
    "HTTP 402: The account associated with this API key has reached its maximum allowed monthly spending limit.",
    "billing",
  ],
  [67, "classifyFailoverReason", "HTTP 402: Weekly usage limit exhausted.", "rate_limit"],
  [
    68,
    "classifyFailoverReason",
    "HTTP 402: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx insufficient credits. Monthly spend limit reached.",
    "billing",
  ],
  [
    69,
    "classifyFailoverReason",
    "HTTP 402: Your credit balance is too low. Monthly limit exceeded.",
    "billing",
  ],
  [
    70,
    "classifyFailoverReason",
    "HTTP 402: Your usage limit has been reached. Please upgrade your plan.",
    "billing",
  ],
  [72, "classifyFailoverReason", "HTTP 404: insufficient credits", "billing"],
  [73, "classifyFailoverReason", "HTTP 404: invalid_api_key", "auth"],
  [74, "classifyFailoverReason", "HTTP 404: No body", "model_not_found"],
  [75, "classifyFailoverReason", "HTTP 404: session not found", "session_expired"],
  [76, "classifyFailoverReason", "HTTP 410", "timeout"],
  [77, "classifyFailoverReason", "HTTP 410: conversation expired", "session_expired"],
  [78, "classifyFailoverReason", "HTTP 410: insufficient credits", "billing"],
  [79, "classifyFailoverReason", "HTTP 410: invalid_api_key", "auth"],
  [80, "classifyFailoverReason", "HTTP 410: No body", "timeout"],
  [81, "classifyFailoverReason", "HTTP 410: No body response", "timeout"],
  [
    82,
    "classifyFailoverReason",
    'HTTP 422: {"type":"error","error":{"type":"server_error","code":"server_error"}}',
    "format",
  ],
  [83, "classifyFailoverReason", "HTTP 422: check open ai req parameter error", "format"],
]);
