import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { prepareWAMessageMedia, type AnyMediaMessageContent } from "baileys";
import { getImageMetadata, resizeToJpeg } from "openclaw/plugin-sdk/media-runtime";
import { createSolidPngBuffer } from "openclaw/plugin-sdk/test-fixtures";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { addWhatsAppImagePreviewFields } from "./image-preview.js";

vi.mock("openclaw/plugin-sdk/media-runtime", async (importOriginal) => {
  const actual = await importOriginal<typeof import("openclaw/plugin-sdk/media-runtime")>();
  return {
    ...actual,
    getImageMetadata: vi.fn(actual.getImageMetadata),
    resizeToJpeg: vi.fn(actual.resizeToJpeg),
  };
});

describe("WhatsApp image preview media upload", () => {
  const image = createSolidPngBuffer(64, 48, { r: 80, g: 120, b: 200 });

  beforeEach(() => {
    vi.resetAllMocks();
  });

  async function uploadImage(content: AnyMediaMessageContent) {
    const warn = vi.fn();
    const logger: NonNullable<Parameters<typeof prepareWAMessageMedia>[1]["logger"]> = {
      level: "silent",
      child: () => logger,
      trace: vi.fn(),
      debug: vi.fn(),
      info: vi.fn(),
      warn,
      error: vi.fn(),
    };
    const upload = vi.fn(async (filePath: string) => {
      expect((await readFile(filePath)).length).toBeGreaterThan(0);
      return { mediaUrl: "https://media.example/image", directPath: "/image" };
    });
    const message = await prepareWAMessageMedia(content, { upload, logger });
    expect(upload).toHaveBeenCalledOnce();
    expect(message.imageMessage).toMatchObject({
      caption: "caption",
      mimetype: "image/png",
      fileSha256: createHash("sha256").update(image).digest(),
      url: "https://media.example/image",
    });
    expect(warn).not.toHaveBeenCalled();
    return message.imageMessage;
  }

  it("uploads the image with a JPEG preview generated by the shared image processor", async () => {
    const content = await addWhatsAppImagePreviewFields({
      image,
      caption: "caption",
      mimetype: "image/png",
    });
    const message = await uploadImage(content);
    expect(message).toMatchObject({ width: 64, height: 48 });
    const thumbnail = Buffer.from(message?.jpegThumbnail ?? []);
    expect(thumbnail.subarray(0, 2)).toEqual(Buffer.from([0xff, 0xd8]));
    expect(await getImageMetadata(thumbnail)).toEqual({ width: 32, height: 24 });
  });

  it.each(["available", "unavailable"] as const)(
    "uploads the original image without another thumbnail attempt when encoding fails and dimensions are %s",
    async (dimensions) => {
      if (dimensions === "unavailable") {
        vi.mocked(getImageMetadata).mockRejectedValueOnce(new Error("Image probe unavailable"));
      }
      vi.mocked(resizeToJpeg).mockRejectedValueOnce(new Error("JPEG encoder unavailable"));
      const content = await addWhatsAppImagePreviewFields({
        image,
        caption: "caption",
        mimetype: "image/png",
      });
      const message = await uploadImage(content);
      expect(message?.jpegThumbnail).toEqual(Buffer.alloc(0));
      if (dimensions === "available") {
        expect(message).toMatchObject({ width: 64, height: 48 });
      }
    },
  );
});
