// Message-tool idempotency key and delivery fingerprint helpers.
// Extracted from message-tool-execution to keep that module within the lint line budget.
import { normalizeOptionalString } from "@openclaw/normalization-core/string-coerce";
import type { ChannelMessageActionName } from "../../channels/plugins/types.public.js";
import { sha256Base64UrlPrefix } from "../../infra/crypto-digest.js";
import type { GatewayCallOptions } from "./gateway.js";

const MESSAGE_TOOL_IDEMPOTENCY_ENVELOPE_PARAM_KEYS = new Set<string>([
  "gatewayToken",
  "gatewayUrl",
  "idempotencyKey",
  "timeoutMs",
] satisfies Array<keyof GatewayCallOptions | "idempotencyKey">);

function stripMessageToolIdempotencyEnvelope(
  params: Record<string, unknown>,
): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const key of Object.keys(params).toSorted()) {
    if (!MESSAGE_TOOL_IDEMPOTENCY_ENVELOPE_PARAM_KEYS.has(key)) {
      out[key] = params[key];
    }
  }
  return out;
}

function canonicalizeMessageToolIdempotencyValue(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((entry) => canonicalizeMessageToolIdempotencyValue(entry));
  }
  if (!value || typeof value !== "object") {
    return value;
  }
  // SAFETY: narrowed by the `typeof value !== "object"` guard above; treat the remaining object as a string-keyed record for canonical ordering.
  const record = value as Record<string, unknown>;
  const out: Record<string, unknown> = {};
  for (const key of Object.keys(record).toSorted()) {
    out[key] = canonicalizeMessageToolIdempotencyValue(record[key]);
  }
  return out;
}

export function normalizeMessageToolIdempotencyKeyPart(value: unknown): string | undefined {
  return normalizeOptionalString(value)?.replace(/[^A-Za-z0-9._:-]+/gu, "_");
}

export function buildMessageToolDeliveryFingerprint(params: {
  action: ChannelMessageActionName;
  params: Record<string, unknown>;
}): string {
  const canonical = JSON.stringify(
    canonicalizeMessageToolIdempotencyValue({
      action: params.action,
      params: stripMessageToolIdempotencyEnvelope(params.params),
    }),
  );
  return sha256Base64UrlPrefix(canonical, 24);
}

export function buildMessageToolAutogeneratedIdempotencyKey(params: {
  runId: string;
  deliveryFingerprint: string;
  operationId: string;
}): string {
  return `${params.runId}:message-tool:${params.deliveryFingerprint}:${params.operationId}`;
}
