/** Validates Gateway install auth and persists a missing token when requested. */
import { normalizeOptionalString } from "@openclaw/normalization-core/string-coerce";
import { formatCliCommand } from "../cli/command-format.js";
import type { ReadConfigFileSnapshotForWriteResult } from "../config/io.js";
import { replaceConfigFile } from "../config/mutate.js";
import type { OpenClawConfig } from "../config/types.js";
import { resolveSecretInputRef } from "../config/types.secrets.js";
import { shouldRequireGatewayTokenForInstall } from "../gateway/auth-install-policy.js";
import { hasAmbiguousGatewayAuthModeConfig } from "../gateway/auth-mode-policy.js";
import { resolveGatewayAuthToken } from "../gateway/auth-token-resolution.js";
import { resolveGatewayAuth } from "../gateway/auth.js";
import {
  formatUnsafeGatewayTailscaleNoAuthMessage,
  isUnsafeGatewayTailscaleNoAuth,
} from "../shared/gateway-tailscale-auth-policy.js";
import { randomToken } from "./random-token.js";

type GatewayInstallTokenOptions = {
  config: OpenClawConfig;
  env: NodeJS.ProcessEnv;
  explicitToken?: string;
  generateIfMissing?: ReadConfigFileSnapshotForWriteResult;
};

type GatewayInstallTokenResolution = {
  unavailableReason?: string;
  warnings: string[];
};

async function maybePersistAutoGeneratedGatewayInstallToken(params: {
  token: string;
  generation: ReadConfigFileSnapshotForWriteResult;
  warnings: string[];
}): Promise<void> {
  try {
    const { snapshot, writeOptions } = params.generation;
    if (snapshot.exists && !snapshot.valid) {
      params.warnings.push(
        "Warning: config file exists but is invalid; skipping token persistence.",
      );
      return;
    }

    const baseConfig = snapshot.exists ? (snapshot.sourceConfig ?? snapshot.config) : {};
    const existingTokenRef = resolveSecretInputRef({
      value: baseConfig.gateway?.auth?.token,
      defaults: baseConfig.secrets?.defaults,
    }).ref;
    const baseConfigToken =
      existingTokenRef || typeof baseConfig.gateway?.auth?.token !== "string"
        ? undefined
        : normalizeOptionalString(baseConfig.gateway.auth.token);
    // Only persist a generated plaintext token when config has no token or SecretRef.
    if (!existingTokenRef && !baseConfigToken) {
      await replaceConfigFile({
        nextConfig: {
          ...baseConfig,
          gateway: {
            ...baseConfig.gateway,
            auth: {
              ...baseConfig.gateway?.auth,
              mode: baseConfig.gateway?.auth?.mode ?? "token",
              token: params.token,
            },
          },
        },
        snapshot,
        writeOptions: {
          baseSnapshot: snapshot,
          ...writeOptions,
          skipRuntimeSnapshotRefresh: true,
        },
        afterWrite: { mode: "auto" },
      });
      return;
    }
    if (baseConfigToken) {
      return;
    }
    params.warnings.push(
      "Warning: gateway.auth.token is SecretRef-managed; skipping plaintext token persistence.",
    );
  } catch (err) {
    params.warnings.push(`Warning: could not persist token to config: ${String(err)}`);
  }
}

function formatAmbiguousGatewayAuthModeReason(): string {
  return [
    "gateway.auth.token and gateway.auth.password are both configured while gateway.auth.mode is unset.",
    `Set ${formatCliCommand("openclaw config set gateway.auth.mode token")} or ${formatCliCommand("openclaw config set gateway.auth.mode password")}.`,
  ].join(" ");
}

/** Validate install auth, using the caller's captured write preparation for token generation. */
export async function resolveGatewayInstallToken(
  options: GatewayInstallTokenOptions,
): Promise<GatewayInstallTokenResolution> {
  const cfg = options.config;
  const warnings: string[] = [];

  if (hasAmbiguousGatewayAuthModeConfig(cfg)) {
    return {
      unavailableReason: formatAmbiguousGatewayAuthModeReason(),
      warnings,
    };
  }

  const resolvedAuth = resolveGatewayAuth({
    authConfig: cfg.gateway?.auth,
    env: options.env,
    tailscaleMode: cfg.gateway?.tailscale?.mode ?? "off",
  });
  const tailscaleMode = cfg.gateway?.tailscale?.mode ?? "off";
  if (isUnsafeGatewayTailscaleNoAuth({ authMode: resolvedAuth.mode, tailscaleMode })) {
    return {
      unavailableReason: formatUnsafeGatewayTailscaleNoAuthMessage(tailscaleMode),
      warnings,
    };
  }
  const needsToken =
    shouldRequireGatewayTokenForInstall(cfg, options.env) && !resolvedAuth.allowTailscale;
  if (!needsToken) {
    return {
      unavailableReason: undefined,
      warnings,
    };
  }

  const resolvedToken = await resolveGatewayAuthToken({
    cfg,
    env: options.env,
    explicitToken: options.explicitToken,
    envFallback: "no-secret-ref",
    unresolvedReasonStyle: "detailed",
  });
  const tokenRefConfigured = resolvedToken.secretRefConfigured;
  const token = resolvedToken.source === "secretRef" ? undefined : resolvedToken.token;
  let unavailableReason: string | undefined;

  if (tokenRefConfigured && resolvedToken.source === "secretRef") {
    warnings.push(
      "gateway.auth.token is SecretRef-managed; install will not persist a resolved token in service environment. Ensure the SecretRef is resolvable in the daemon runtime context.",
    );
  } else if (tokenRefConfigured && !token) {
    unavailableReason = `gateway.auth.token SecretRef is configured but unresolved (${resolvedToken.unresolvedRefReason ?? "unknown reason"}).`;
  }

  if (!token && !tokenRefConfigured && options.generateIfMissing) {
    const generatedToken = randomToken();
    warnings.push("No gateway token found. Auto-generated one and saving to config.");
    await maybePersistAutoGeneratedGatewayInstallToken({
      token: generatedToken,
      generation: options.generateIfMissing,
      warnings,
    });
  }

  return {
    unavailableReason,
    warnings,
  };
}
