export const LLAMA_SERVER_DEFAULT_ORIGIN = "http://127.0.0.1:8080";
export const LLAMA_SERVER_DEFAULT_API_KEY_ENV_VAR = "LLAMA_SERVER_API_KEY";
export const LLAMA_SERVER_DISCOVERY_TIMEOUT_MS = 5_000;
export const LLAMA_SERVER_DISCOVERY_CACHE_TTL_MS = 30_000;
