import * as agentsModelsSkills from "./agents-models-skills.js";
import * as agentsWorkspace from "./agents-workspace.js";
import * as artifacts from "./artifacts.js";
import * as commands from "./commands.js";
import * as skillHistory from "./skill-history.js";
import * as skillLibrary from "./skill-library.js";
import * as transcripts from "./transcripts.js";

export const AgentSkillProtocolSchemas = {
  TranscriptSessionSummary: transcripts.TranscriptSessionSummarySchema,
  TranscriptsListParams: transcripts.TranscriptsListParamsSchema,
  TranscriptsListResult: transcripts.TranscriptsListResultSchema,
  TranscriptsGetParams: transcripts.TranscriptsGetParamsSchema,
  TranscriptsGetResult: transcripts.TranscriptsGetResultSchema,
  SkillsLibraryListParams: skillLibrary.SkillsLibraryListParamsSchema,
  SkillsLibraryReadParams: skillLibrary.SkillsLibraryReadParamsSchema,
  SkillsLibrarySaveParams: skillLibrary.SkillsLibrarySaveParamsSchema,
  SkillsLibraryMutateParams: skillLibrary.SkillsLibraryMutateParamsSchema,
  SkillsLibraryActivateParams: skillLibrary.SkillsLibraryActivateParamsSchema,
  SkillsLibraryImportParams: skillLibrary.SkillsLibraryImportParamsSchema,
  SkillsLibraryUploadParams: skillLibrary.SkillsLibraryUploadParamsSchema,
  AgentKind: agentsModelsSkills.AgentKindSchema,
  AgentSummary: agentsModelsSkills.AgentSummarySchema,
  AgentsCreateParams: agentsModelsSkills.AgentsCreateParamsSchema,
  AgentsCreateResult: agentsModelsSkills.AgentsCreateResultSchema,
  AgentsUpdateParams: agentsModelsSkills.AgentsUpdateParamsSchema,
  AgentsUpdateResult: agentsModelsSkills.AgentsUpdateResultSchema,
  AgentsDeleteParams: agentsModelsSkills.AgentsDeleteParamsSchema,
  AgentsDeleteResult: agentsModelsSkills.AgentsDeleteResultSchema,
  AgentsFileEntry: agentsModelsSkills.AgentsFileEntrySchema,
  AgentsFilesListParams: agentsModelsSkills.AgentsFilesListParamsSchema,
  AgentsFilesListResult: agentsModelsSkills.AgentsFilesListResultSchema,
  AgentsFilesGetParams: agentsModelsSkills.AgentsFilesGetParamsSchema,
  AgentsFilesGetResult: agentsModelsSkills.AgentsFilesGetResultSchema,
  AgentsFilesSetParams: agentsModelsSkills.AgentsFilesSetParamsSchema,
  AgentsFilesSetResult: agentsModelsSkills.AgentsFilesSetResultSchema,
  AgentsWorkspaceEntry: agentsWorkspace.AgentsWorkspaceEntrySchema,
  AgentsWorkspaceFile: agentsWorkspace.AgentsWorkspaceFileSchema,
  AgentsWorkspaceListParams: agentsWorkspace.AgentsWorkspaceListParamsSchema,
  AgentsWorkspaceListResult: agentsWorkspace.AgentsWorkspaceListResultSchema,
  AgentsWorkspaceGetParams: agentsWorkspace.AgentsWorkspaceGetParamsSchema,
  AgentsWorkspaceGetResult: agentsWorkspace.AgentsWorkspaceGetResultSchema,
  ArtifactSummary: artifacts.ArtifactSummarySchema,
  ArtifactsListParams: artifacts.ArtifactsListParamsSchema,
  ArtifactsListResult: artifacts.ArtifactsListResultSchema,
  ArtifactsGetParams: artifacts.ArtifactsGetParamsSchema,
  ArtifactsGetResult: artifacts.ArtifactsGetResultSchema,
  ArtifactsDownloadParams: artifacts.ArtifactsDownloadParamsSchema,
  ArtifactsDownloadResult: artifacts.ArtifactsDownloadResultSchema,
  AgentsListParams: agentsModelsSkills.AgentsListParamsSchema,
  AgentsListResult: agentsModelsSkills.AgentsListResultSchema,
  ModelChoice: agentsModelsSkills.ModelChoiceSchema,
  ModelsAuthLogoutParams: agentsModelsSkills.ModelsAuthLogoutParamsSchema,
  ModelsAuthOrderSetParams: agentsModelsSkills.ModelsAuthOrderSetParamsSchema,
  ModelsAuthStatusParams: agentsModelsSkills.ModelsAuthStatusParamsSchema,
  ModelsListParams: agentsModelsSkills.ModelsListParamsSchema,
  ModelsListResult: agentsModelsSkills.ModelsListResultSchema,
  ModelsProbeParams: agentsModelsSkills.ModelsProbeParamsSchema,
  ModelsProbeTargetResult: agentsModelsSkills.ModelsProbeTargetResultSchema,
  ModelsProbeResult: agentsModelsSkills.ModelsProbeResultSchema,
  CommandEntry: commands.CommandEntrySchema,
  CommandsListParams: commands.CommandsListParamsSchema,
  CommandsListResult: commands.CommandsListResultSchema,
  SkillsStatusParams: agentsModelsSkills.SkillsStatusParamsSchema,
  ToolsCatalogParams: agentsModelsSkills.ToolsCatalogParamsSchema,
  GitHubIdentitySource: agentsModelsSkills.GitHubIdentitySourceSchema,
  GitHubAuthor: agentsModelsSkills.GitHubAuthorSchema,
  GitHubIdentityFacts: agentsModelsSkills.GitHubIdentityFactsSchema,
  GitHubIdentityScope: agentsModelsSkills.GitHubIdentityScopeSchema,
  GitHubSelectedIdentity: agentsModelsSkills.GitHubSelectedIdentitySchema,
  ToolsGitHubStatusParams: agentsModelsSkills.ToolsGitHubStatusParamsSchema,
  ToolsGitHubStatusResult: agentsModelsSkills.ToolsGitHubStatusResultSchema,
  ToolsGitHubManagedConfigureParams: agentsModelsSkills.ToolsGitHubManagedConfigureParamsSchema,
  ToolsGitHubInheritConfigureParams: agentsModelsSkills.ToolsGitHubInheritConfigureParamsSchema,
  ToolsGitHubConfigureParams: agentsModelsSkills.ToolsGitHubConfigureParamsSchema,
  ToolsGitHubAuthorizeStartParams: agentsModelsSkills.ToolsGitHubAuthorizeStartParamsSchema,
  ToolsGitHubAuthorizeStartResult: agentsModelsSkills.ToolsGitHubAuthorizeStartResultSchema,
  ToolsGitHubAuthorizePollParams: agentsModelsSkills.ToolsGitHubAuthorizePollParamsSchema,
  ToolsGitHubAuthorizePendingResult: agentsModelsSkills.ToolsGitHubAuthorizePendingResultSchema,
  ToolsGitHubAuthorizeSlowDownResult: agentsModelsSkills.ToolsGitHubAuthorizeSlowDownResultSchema,
  ToolsGitHubAuthorizeAccessDeniedResult:
    agentsModelsSkills.ToolsGitHubAuthorizeAccessDeniedResultSchema,
  ToolsGitHubAuthorizeExpiredResult: agentsModelsSkills.ToolsGitHubAuthorizeExpiredResultSchema,
  ToolsGitHubAuthorizeIncorrectDeviceCodeResult:
    agentsModelsSkills.ToolsGitHubAuthorizeIncorrectDeviceCodeResultSchema,
  ToolsGitHubAuthorizeNetworkErrorResult:
    agentsModelsSkills.ToolsGitHubAuthorizeNetworkErrorResultSchema,
  ToolsGitHubAuthorizeFailedResult: agentsModelsSkills.ToolsGitHubAuthorizeFailedResultSchema,
  ToolsGitHubAuthorizeSuccessResult: agentsModelsSkills.ToolsGitHubAuthorizeSuccessResultSchema,
  ToolsGitHubAuthorizePollResult: agentsModelsSkills.ToolsGitHubAuthorizePollResultSchema,
  ToolsGitHubAuthorizeCancelParams: agentsModelsSkills.ToolsGitHubAuthorizeCancelParamsSchema,
  ToolsGitHubAuthorizeCancelResult: agentsModelsSkills.ToolsGitHubAuthorizeCancelResultSchema,
  ToolCatalogProfile: agentsModelsSkills.ToolCatalogProfileSchema,
  ToolCatalogEntry: agentsModelsSkills.ToolCatalogEntrySchema,
  ToolCatalogGroup: agentsModelsSkills.ToolCatalogGroupSchema,
  ToolsCatalogResult: agentsModelsSkills.ToolsCatalogResultSchema,
  ToolsEffectiveParams: agentsModelsSkills.ToolsEffectiveParamsSchema,
  ToolsEffectiveEntry: agentsModelsSkills.ToolsEffectiveEntrySchema,
  ToolsEffectiveGroup: agentsModelsSkills.ToolsEffectiveGroupSchema,
  ToolsEffectiveNotice: agentsModelsSkills.ToolsEffectiveNoticeSchema,
  ToolsEffectiveResult: agentsModelsSkills.ToolsEffectiveResultSchema,
  ToolsInvokeParams: agentsModelsSkills.ToolsInvokeParamsSchema,
  ToolsInvokeError: agentsModelsSkills.ToolsInvokeErrorSchema,
  ToolsInvokeResult: agentsModelsSkills.ToolsInvokeResultSchema,
  SkillsBinsParams: agentsModelsSkills.SkillsBinsParamsSchema,
  SkillsBinsResult: agentsModelsSkills.SkillsBinsResultSchema,
  SkillsSearchParams: agentsModelsSkills.SkillsSearchParamsSchema,
  SkillsSearchResult: agentsModelsSkills.SkillsSearchResultSchema,
  SkillsDetailParams: agentsModelsSkills.SkillsDetailParamsSchema,
  SkillsDetailResult: agentsModelsSkills.SkillsDetailResultSchema,
  SkillsCuratorActionParams: agentsModelsSkills.SkillsCuratorActionParamsSchema,
  SkillsCuratorActionResult: agentsModelsSkills.SkillsCuratorActionResultSchema,
  SkillsCuratorStatusParams: agentsModelsSkills.SkillsCuratorStatusParamsSchema,
  SkillsCuratorStatusResult: agentsModelsSkills.SkillsCuratorStatusResultSchema,
  SkillsProposalsListParams: agentsModelsSkills.SkillsProposalsListParamsSchema,
  SkillsProposalsListResult: agentsModelsSkills.SkillsProposalsListResultSchema,
  SkillsWorkshopReadParams: agentsModelsSkills.SkillsWorkshopReadParamsSchema,
  SkillsWorkshopReadResult: agentsModelsSkills.SkillsWorkshopReadResultSchema,
  SkillsProposalEvaluateParams: agentsModelsSkills.SkillsProposalEvaluateParamsSchema,
  SkillsProposalEvaluateResult: agentsModelsSkills.SkillsProposalEvaluateResultSchema,
  SkillsProposalEventsListParams: agentsModelsSkills.SkillsProposalEventsListParamsSchema,
  SkillsProposalEventsListResult: agentsModelsSkills.SkillsProposalEventsListResultSchema,
  SkillsProposalHistoryStatusParams: skillHistory.SkillsProposalHistoryStatusParamsSchema,
  SkillsProposalHistoryScanParams: skillHistory.SkillsProposalHistoryScanParamsSchema,
  SkillsProposalHistoryScanResult: skillHistory.SkillsProposalHistoryScanResultSchema,
  SkillsProposalInspectParams: agentsModelsSkills.SkillsProposalInspectParamsSchema,
  SkillsProposalInspectResult: agentsModelsSkills.SkillsProposalInspectResultSchema,
  SkillsProposalCreateParams: agentsModelsSkills.SkillsProposalCreateParamsSchema,
  SkillsProposalUpdateParams: agentsModelsSkills.SkillsProposalUpdateParamsSchema,
  SkillsProposalReviseParams: agentsModelsSkills.SkillsProposalReviseParamsSchema,
  SkillsProposalRequestRevisionParams: agentsModelsSkills.SkillsProposalRequestRevisionParamsSchema,
  SkillsProposalRequestRevisionResult: agentsModelsSkills.SkillsProposalRequestRevisionResultSchema,
  SkillsProposalDecisionParams: agentsModelsSkills.SkillsProposalDecisionParamsSchema,
  SkillsProposalActionParams: agentsModelsSkills.SkillsProposalActionParamsSchema,
  SkillsProposalApplyResult: agentsModelsSkills.SkillsProposalApplyResultSchema,
  SkillsProposalRecordResult: agentsModelsSkills.SkillsProposalRecordResultSchema,
  SkillsSecurityVerdictsParams: agentsModelsSkills.SkillsSecurityVerdictsParamsSchema,
  SkillsSecurityVerdictsResult: agentsModelsSkills.SkillsSecurityVerdictsResultSchema,
  SkillsSkillCardParams: agentsModelsSkills.SkillsSkillCardParamsSchema,
  SkillsSkillCardResult: agentsModelsSkills.SkillsSkillCardResultSchema,
  SkillsUploadBeginParams: agentsModelsSkills.SkillsUploadBeginParamsSchema,
  SkillsUploadChunkParams: agentsModelsSkills.SkillsUploadChunkParamsSchema,
  SkillsUploadCommitParams: agentsModelsSkills.SkillsUploadCommitParamsSchema,
  SkillsInstallParams: agentsModelsSkills.SkillsInstallParamsSchema,
  SkillsUpdateParams: agentsModelsSkills.SkillsUpdateParamsSchema,
  TranscriptsExportParams: transcripts.TranscriptsExportParamsSchema,
  TranscriptsExportResult: transcripts.TranscriptsExportResultSchema,
  TranscriptsStatusParams: transcripts.TranscriptsStatusParamsSchema,
  TranscriptsStatusResult: transcripts.TranscriptsStatusResultSchema,
} as const;
