import * as agent from "./agent.js";
import * as desktop from "./desktop.js";
import * as environments from "./environments.js";
import * as fsSchemas from "./fs.js";
import * as projects from "./projects.js";
import * as systemInfo from "./system-info.js";
import * as worktrees from "./worktrees.js";

export const AgentControlProtocolSchemas = {
  EnvironmentStatus: environments.EnvironmentStatusSchema,
  WorkerEnvironmentState: environments.WorkerEnvironmentStateSchema,
  WorkerTunnelStatus: environments.WorkerTunnelStatusSchema,
  WorkerDesktopAppId: environments.WorkerDesktopAppIdSchema,
  RequiredNodeCommandState: environments.RequiredNodeCommandStateSchema,
  RequiredNodeCommand: environments.RequiredNodeCommandSchema,
  WorkerEnvironmentMetadata: environments.WorkerEnvironmentMetadataSchema,
  WorkerSlotSummary: environments.WorkerSlotSummarySchema,
  EnvironmentSummary: environments.EnvironmentSummarySchema,
  EnvironmentsCreateParams: environments.EnvironmentsCreateParamsSchema,
  EnvironmentsCreateResult: environments.EnvironmentsCreateResultSchema,
  EnvironmentsDestroyParams: environments.EnvironmentsDestroyParamsSchema,
  EnvironmentsDestroyResult: environments.EnvironmentsDestroyResultSchema,
  EnvironmentsListParams: environments.EnvironmentsListParamsSchema,
  EnvironmentsListResult: environments.EnvironmentsListResultSchema,
  EnvironmentsStatusParams: environments.EnvironmentsStatusParamsSchema,
  EnvironmentsStatusResult: environments.EnvironmentsStatusResultSchema,
  WorkerDesktopObserveParams: environments.WorkerDesktopObserveParamsSchema,
  WorkerDesktopObserveResult: environments.WorkerDesktopObserveResultSchema,
  WorkerDesktopLaunchParams: environments.WorkerDesktopLaunchParamsSchema,
  WorkerDesktopLaunchResult: environments.WorkerDesktopLaunchResultSchema,
  ProjectCheckout: projects.ProjectCheckoutSchema,
  ProjectSummary: projects.ProjectSummarySchema,
  DesktopSource: desktop.DesktopSourceSchema,
  DesktopObserveParams: desktop.DesktopObserveParamsSchema,
  DesktopObserveResult: desktop.DesktopObserveResultSchema,
  DesktopLaunchParams: desktop.DesktopLaunchParamsSchema,
  SystemInfoParams: systemInfo.SystemInfoParamsSchema,
  SystemInfoResult: systemInfo.SystemInfoResultSchema,
  AgentEvent: agent.AgentEventSchema,
  ConversationSendParams: agent.ConversationSendParamsSchema,
  ConversationSendResult: agent.ConversationSendResultSchema,
  ConversationListItem: agent.ConversationListItemSchema,
  ConversationListParams: agent.ConversationListParamsSchema,
  ConversationListResult: agent.ConversationListResultSchema,
  ConversationTurnCancelParams: agent.ConversationTurnCancelParamsSchema,
  ConversationTurnCancelResult: agent.ConversationTurnCancelResultSchema,
  ConversationTurnParams: agent.ConversationTurnParamsSchema,
  ConversationTurnReply: agent.ConversationTurnReplySchema,
  ConversationTurnResult: agent.ConversationTurnResultSchema,
  MessageActionParams: agent.MessageActionParamsSchema,
  SendParams: agent.SendParamsSchema,
  PollParams: agent.PollParamsSchema,
  AgentParams: agent.AgentParamsSchema,
  AgentIdentityParams: agent.AgentIdentityParamsSchema,
  AgentIdentityResult: agent.AgentIdentityResultSchema,
  AgentWaitParams: agent.AgentWaitParamsSchema,
  WakeParams: agent.WakeParamsSchema,
  ProjectRecord: projects.ProjectRecordSchema,
  ProjectRecentFolder: projects.ProjectRecentFolderSchema,
  ProjectRecentProject: projects.ProjectRecentProjectSchema,
  ProjectRecent: projects.ProjectRecentSchema,
  ProjectsListParams: projects.ProjectsListParamsSchema,
  ProjectsListResult: projects.ProjectsListResultSchema,
  ProjectsRegisterParams: projects.ProjectsRegisterParamsSchema,
  ProjectsRegisterResult: projects.ProjectsRegisterResultSchema,
  ProjectsAddParams: projects.ProjectsAddParamsSchema,
  ProjectsAddResult: projects.ProjectsAddResultSchema,
  RemoteProject: projects.RemoteProjectSchema,
  ProjectsSearchRemoteParams: projects.ProjectsSearchRemoteParamsSchema,
  ProjectsSearchRemoteResult: projects.ProjectsSearchRemoteResultSchema,
  ProjectsRemoveParams: projects.ProjectsRemoveParamsSchema,
  ProjectsRemoveResult: projects.ProjectsRemoveResultSchema,
  WorktreeRecord: worktrees.WorktreeRecordSchema,
  WorktreesListParams: worktrees.WorktreesListParamsSchema,
  WorktreesListResult: worktrees.WorktreesListResultSchema,
  WorktreesCreateParams: worktrees.WorktreesCreateParamsSchema,
  WorktreesRemoveParams: worktrees.WorktreesRemoveParamsSchema,
  WorktreesRemoveResult: worktrees.WorktreesRemoveResultSchema,
  WorktreesRestoreParams: worktrees.WorktreesRestoreParamsSchema,
  WorktreesGcParams: worktrees.WorktreesGcParamsSchema,
  WorktreesGcResult: worktrees.WorktreesGcResultSchema,
  WorktreeBranch: worktrees.WorktreeBranchSchema,
  WorktreeRepositoryStatus: worktrees.WorktreeRepositoryStatusSchema,
  WorktreesBranchesParams: worktrees.WorktreesBranchesParamsSchema,
  WorktreesBranchesResult: worktrees.WorktreesBranchesResultSchema,
  FsDirEntry: fsSchemas.FsDirEntrySchema,
  FsListDirParams: fsSchemas.FsListDirParamsSchema,
  FsListDirResult: fsSchemas.FsListDirResultSchema,
} as const;
