import * as participants from "./session-participant.js";
import * as sessionsCatalog from "./sessions-catalog.js";
import {
  SessionsResolveCandidateSchema,
  SessionsResolveParamsSchema,
  SessionsResolveResultSchema,
} from "./sessions-resolve.js";
import * as sessions from "./sessions.js";

export const SessionCoreProtocolSchemas = {
  SessionPermissionMode: sessions.SessionPermissionModeSchema,
  SessionsListParams: sessions.SessionsListParamsSchema,
  SessionCatalogCapabilities: sessionsCatalog.SessionCatalogCapabilitiesSchema,
  SessionCatalogDescriptor: sessionsCatalog.SessionCatalogDescriptorSchema,
  SessionCatalogPullRequestSummary: sessionsCatalog.SessionCatalogPullRequestSummarySchema,
  SessionCatalogSession: sessionsCatalog.SessionCatalogSessionSchema,
  SessionCatalogHost: sessionsCatalog.SessionCatalogHostSchema,
  SessionCatalog: sessionsCatalog.SessionCatalogSchema,
  SessionCatalogTranscriptItem: sessionsCatalog.SessionCatalogTranscriptItemSchema,
  SessionsCatalogListParams: sessionsCatalog.SessionsCatalogListParamsSchema,
  SessionsCatalogListResult: sessionsCatalog.SessionsCatalogListResultSchema,
  SessionsCatalogReadParams: sessionsCatalog.SessionsCatalogReadParamsSchema,
  SessionsCatalogReadResult: sessionsCatalog.SessionsCatalogReadResultSchema,
  SessionsCatalogContinueParams: sessionsCatalog.SessionsCatalogContinueParamsSchema,
  SessionsCatalogContinueResult: sessionsCatalog.SessionsCatalogContinueResultSchema,
  SessionsCatalogArchiveParams: sessionsCatalog.SessionsCatalogArchiveParamsSchema,
  SessionsCatalogArchiveResult: sessionsCatalog.SessionsCatalogArchiveResultSchema,
  SessionsCatalogStartTerminalParams: sessionsCatalog.SessionsCatalogStartTerminalParamsSchema,
  SessionsCatalogStartTerminalResult: sessionsCatalog.SessionsCatalogStartTerminalResultSchema,
  SessionsCleanupParams: sessions.SessionsCleanupParamsSchema,
  SessionsPreviewParams: sessions.SessionsPreviewParamsSchema,
  SessionsDescribeParams: sessions.SessionsDescribeParamsSchema,
  SessionsResolveCandidate: SessionsResolveCandidateSchema,
  SessionsResolveParams: SessionsResolveParamsSchema,
  SessionsResolveResult: SessionsResolveResultSchema,
  SessionsSearchHit: sessions.SessionsSearchHitSchema,
  SessionsSearchParams: sessions.SessionsSearchParamsSchema,
  SessionsSearchResult: sessions.SessionsSearchResultSchema,
  SessionCompactionCheckpoint: sessions.SessionCompactionCheckpointSchema,
  SessionOperationEvent: sessions.SessionOperationEventSchema,
  SessionCreatedActor: sessions.SessionCreatedActorSchema,
  SessionParticipantIdentity: participants.SessionParticipantIdentitySchema,
  SessionParticipant: participants.SessionParticipantSchema,
  SessionPerson: participants.SessionPersonSchema,
  SessionOwner: sessions.SessionOwnerSchema,
  SessionObserverHealth: sessions.SessionObserverHealthSchema,
  SessionObserverPlanProgress: sessions.SessionObserverPlanProgressSchema,
  SessionObserverDigest: sessions.SessionObserverDigestSchema,
  SessionCompanionExchange: sessions.SessionCompanionExchangeSchema,
  SessionRow: sessions.SessionRowSchema,
  SessionsCompanionAskParams: sessions.SessionsCompanionAskParamsSchema,
  SessionsCompanionAskResult: sessions.SessionsCompanionAskResultSchema,
  SessionsCompanionResetParams: sessions.SessionsCompanionResetParamsSchema,
  SessionsCompanionResetResult: sessions.SessionsCompanionResetResultSchema,
  SessionsCompanionStateParams: sessions.SessionsCompanionStateParamsSchema,
  SessionsCompanionStateResult: sessions.SessionsCompanionStateResultSchema,
  SessionsObserverVisibilityParams: sessions.SessionsObserverVisibilityParamsSchema,
  SessionsObserverVisibilityResult: sessions.SessionsObserverVisibilityResultSchema,
} as const;
