import * as nodes from "./nodes.js";

export const NodeProtocolSchemas = {
  NodePairListParams: nodes.NodePairListParamsSchema,
  NodePairApproveParams: nodes.NodePairApproveParamsSchema,
  NodePairRejectParams: nodes.NodePairRejectParamsSchema,
  NodePairRemoveParams: nodes.NodePairRemoveParamsSchema,
  NodeRenameParams: nodes.NodeRenameParamsSchema,
  NodeListParams: nodes.NodeListParamsSchema,
  NodePluginToolDescriptor: nodes.NodePluginToolDescriptorSchema,
  NodePluginToolsUpdateParams: nodes.NodePluginToolsUpdateParamsSchema,
  NodeSkillDescriptor: nodes.NodeSkillDescriptorSchema,
  NodeSkillsUpdateParams: nodes.NodeSkillsUpdateParamsSchema,
  NodePendingAckParams: nodes.NodePendingAckParamsSchema,
  NodeDescribeParams: nodes.NodeDescribeParamsSchema,
  NodeInvokeParams: nodes.NodeInvokeParamsSchema,
  NodeInvokeInputEvent: nodes.NodeInvokeInputEventSchema,
  NodeInvokeProgressParams: nodes.NodeInvokeProgressParamsSchema,
  NodeInvokeResultParams: nodes.NodeInvokeResultParamsSchema,
  NodeInvokeRequestEvent: nodes.NodeInvokeRequestEventSchema,
  NodeEventParams: nodes.NodeEventParamsSchema,
  NodeEventResult: nodes.NodeEventResultSchema,
  NodePresenceAlivePayload: nodes.NodePresenceAlivePayloadSchema,
  NodePresenceAliveReason: nodes.NodePresenceAliveReasonSchema,
  NodePresenceActivityPayload: nodes.NodePresenceActivityPayloadSchema,
  NodeHostStatsPayload: nodes.NodeHostStatsPayloadSchema,
  NodePendingDrainParams: nodes.NodePendingDrainParamsSchema,
  NodePendingDrainResult: nodes.NodePendingDrainResultSchema,
  NodePendingEnqueueParams: nodes.NodePendingEnqueueParamsSchema,
  NodePendingEnqueueResult: nodes.NodePendingEnqueueResultSchema,
} as const;
