import * as config from "./config.js";
import * as devices from "./devices.js";
import * as frames from "./frames.js";
import * as hooks from "./hooks.js";
import * as logsChat from "./logs-chat.js";
import * as pluginApprovals from "./plugin-approvals.js";
import * as plugins from "./plugins.js";
import * as updateRuns from "./update-runs.js";

export const PluginLifecycleProtocolSchemas = {
  CapabilityConsentErrorDetails: plugins.CapabilityConsentErrorDetailsSchema,
  HooksStatusParams: hooks.HooksStatusParamsSchema,
  PluginApprovalRequestParams: pluginApprovals.PluginApprovalRequestParamsSchema,
  PluginApprovalResolveParams: pluginApprovals.PluginApprovalResolveParamsSchema,
  PluginCatalogClawHubInstall: plugins.PluginCatalogClawHubInstallSchema,
  PluginCatalogEntry: plugins.PluginCatalogEntrySchema,
  PluginCatalogInstallAction: plugins.PluginCatalogInstallActionSchema,
  PluginCatalogOfficialInstall: plugins.PluginCatalogOfficialInstallSchema,
  PluginControlUiDescriptor: plugins.PluginControlUiDescriptorSchema,
  PluginControlUiModule: plugins.PluginControlUiModuleSchema,
  PluginControlUiDiagnostic: plugins.PluginControlUiDiagnosticSchema,
  PluginsControlUiListParams: plugins.PluginsControlUiListParamsSchema,
  PluginsControlUiReloadParams: plugins.PluginsControlUiReloadParamsSchema,
  PluginsControlUiCatalog: plugins.PluginsControlUiCatalogSchema,
  PluginsControlUiChangedEvent: plugins.PluginsControlUiChangedEventSchema,
  PluginsControlUiReportParams: plugins.PluginsControlUiReportParamsSchema,
  PluginsControlUiStatusParams: plugins.PluginsControlUiStatusParamsSchema,
  PluginsControlUiStatusResult: plugins.PluginsControlUiStatusResultSchema,
  PluginDeclaredSurface: plugins.PluginDeclaredSurfaceSchema,
  PluginDeclaredSurfaceWidening: plugins.PluginDeclaredSurfaceWideningSchema,
  PluginHookGrant: plugins.PluginHookGrantSchema,
  PluginInspectSource: plugins.PluginInspectSourceSchema,
  PluginInstallTrust: plugins.PluginInstallTrustSchema,
  PluginOperatorGrants: plugins.PluginOperatorGrantsSchema,
  PluginSearchPackage: plugins.PluginSearchPackageSchema,
  PluginSearchResultEntry: plugins.PluginSearchResultEntrySchema,
  PluginsInspectParams: plugins.PluginsInspectParamsSchema,
  PluginsInspectResult: plugins.PluginsInspectResultSchema,
  PluginsInstallParams: plugins.PluginsInstallParamsSchema,
  PluginsInstallResult: plugins.PluginsInstallResultSchema,
  PluginsListParams: plugins.PluginsListParamsSchema,
  PluginsListResult: plugins.PluginsListResultSchema,
  PluginsRefreshParams: plugins.PluginsRefreshParamsSchema,
  PluginsRefreshResult: plugins.PluginsRefreshResultSchema,
  PluginsSearchParams: plugins.PluginsSearchParamsSchema,
  PluginsSearchResult: plugins.PluginsSearchResultSchema,
  PluginsSessionActionFailureResult: plugins.PluginsSessionActionFailureResultSchema,
  PluginsSessionActionParams: plugins.PluginsSessionActionParamsSchema,
  PluginsSessionActionResult: plugins.PluginsSessionActionResultSchema,
  PluginsSessionActionSuccessResult: plugins.PluginsSessionActionSuccessResultSchema,
  PluginsSetEnabledParams: plugins.PluginsSetEnabledParamsSchema,
  PluginsSetEnabledResult: plugins.PluginsSetEnabledResultSchema,
  PluginsUiDescriptorsParams: plugins.PluginsUiDescriptorsParamsSchema,
  PluginsUiDescriptorsResult: plugins.PluginsUiDescriptorsResultSchema,
  PluginsUninstallParams: plugins.PluginsUninstallParamsSchema,
  PluginsUninstallResult: plugins.PluginsUninstallResultSchema,
  DevicePairListParams: devices.DevicePairListParamsSchema,
  DevicePairApproveParams: devices.DevicePairApproveParamsSchema,
  DevicePairRejectParams: devices.DevicePairRejectParamsSchema,
  DevicePairRemoveParams: devices.DevicePairRemoveParamsSchema,
  DevicePairSetupCodeParams: devices.DevicePairSetupCodeParamsSchema,
  DevicePairSetupCodeResult: devices.DevicePairSetupCodeResultSchema,
  DevicePairSetupStatusParams: devices.DevicePairSetupStatusParamsSchema,
  DevicePairSetupStatusResult: devices.DevicePairSetupStatusResultSchema,
  DevicePairRenameParams: devices.DevicePairRenameParamsSchema,
  DeviceTokenRotateParams: devices.DeviceTokenRotateParamsSchema,
  DeviceTokenRotateResult: devices.DeviceTokenRotateResultSchema,
  DeviceTokenRevokeParams: devices.DeviceTokenRevokeParamsSchema,
  ScopeUpgradeRequest: devices.ScopeUpgradeRequestSchema,
  ScopeUpgradeWait: devices.ScopeUpgradeWaitSchema,
  ScopeUpgradeRegistration: devices.ScopeUpgradeRegistrationSchema,
  ScopeUpgradeApproved: devices.ScopeUpgradeApprovedSchema,
  ScopeUpgradeRejected: devices.ScopeUpgradeRejectedSchema,
  ScopeUpgradeExpired: devices.ScopeUpgradeExpiredSchema,
  ScopeUpgradeResult: devices.ScopeUpgradeResultSchema,
  DevicePairRequestedEvent: devices.DevicePairRequestedEventSchema,
  DevicePairResolvedEvent: devices.DevicePairResolvedEventSchema,
  DevicePairSetupCompletedEvent: devices.DevicePairSetupCompletedEventSchema,
  DevicePairSetupDeliveryUncertainEvent: devices.DevicePairSetupDeliveryUncertainEventSchema,
  ChatHistoryParams: logsChat.ChatHistoryParamsSchema,
  ChatStartupParams: logsChat.ChatStartupParamsSchema,
  ChatHistoryDeltaResult: logsChat.ChatHistoryDeltaResultSchema,
  ChatHistoryResetResult: logsChat.ChatHistoryResetResultSchema,
  ChatHistoryCursorResult: logsChat.ChatHistoryCursorResultSchema,
  ChatMetadataParams: logsChat.ChatMetadataParamsSchema,
  ChatMessageGetParams: logsChat.ChatMessageGetParamsSchema,
  ChatMessageGetResult: logsChat.ChatMessageGetResultSchema,
  ChatToolTitlesParams: logsChat.ChatToolTitlesParamsSchema,
  ChatToolTitlesResult: logsChat.ChatToolTitlesResultSchema,
  ChatSendParams: logsChat.ChatSendParamsSchema,
  ChatAbortParams: logsChat.ChatAbortParamsSchema,
  ChatInjectParams: logsChat.ChatInjectParamsSchema,
  ChatRunStartupPhase: logsChat.ChatRunStartupPhaseSchema,
  ChatStatusEvent: logsChat.ChatStatusEventSchema,
  ChatDeltaEvent: logsChat.ChatDeltaEventSchema,
  ChatFinalEvent: logsChat.ChatFinalEventSchema,
  ChatAbortedEvent: logsChat.ChatAbortedEventSchema,
  ChatErrorEvent: logsChat.ChatErrorEventSchema,
  ChatEvent: logsChat.ChatEventSchema,
  UpdateStatusParams: config.UpdateStatusParamsSchema,
  UpdateStatusResult: config.UpdateStatusResultSchema,
  UpdateAvailable: config.UpdateAvailableSchema,
  UpdateScheduleState: config.UpdateScheduleStateSchema,
  UpdateHoldParams: config.UpdateHoldParamsSchema,
  UpdateHoldResult: config.UpdateHoldResultSchema,
  UpdateRunParams: config.UpdateRunParamsSchema,
  UpdateRunRecord: updateRuns.UpdateRunRecordSchema,
  UpdateRunResult: updateRuns.UpdateRunResultSchema,
  UpdateRunsGetParams: updateRuns.UpdateRunsGetParamsSchema,
  UpdateRunsGetResult: updateRuns.UpdateRunsGetResultSchema,
  UpdateRunsListParams: updateRuns.UpdateRunsListParamsSchema,
  UpdateRunsListResult: updateRuns.UpdateRunsListResultSchema,
  UpdateRunChangedEvent: updateRuns.UpdateRunChangedEventSchema,
  UpdateReportParams: config.UpdateReportParamsSchema,
  UpdateReportResult: config.UpdateReportResultSchema,
  TickEvent: frames.TickEventSchema,
  ShutdownEvent: frames.ShutdownEventSchema,
} as const;
