import type { ChannelsProps } from "./view.types.ts";

export function createChannelsViewProps(
  snapshot: ChannelsProps["snapshot"],
  pairingSnapshot: ChannelsProps["pairingSnapshot"],
  overrides?: Partial<ChannelsProps>,
): ChannelsProps {
  return {
    connected: true,
    loading: false,
    snapshot,
    pluginCatalog: null,
    pluginIconUrls: {},
    lastError: null,
    lastSuccessAt: null,
    pairingLoading: false,
    pairingSnapshot,
    pairingError: null,
    pairingLastSuccessAt: null,
    pairingBusyRequestId: null,
    pairingChannelFilter: null,
    pairingAccountFilter: null,
    pairingPrompt: null,
    pairingNotice: null,
    canManagePairing: true,
    canAdmin: true,
    whatsappMessage: null,
    whatsappQrDataUrl: null,
    whatsappConnected: null,
    whatsappBusy: false,
    configSchema: null,
    configSchemaLoading: false,
    configForm: null,
    configUiHints: {},
    configSaving: false,
    configError: null,
    configFormDirty: false,
    showAdvancedSettings: false,
    nostrProfileFormState: null,
    nostrProfileAccountId: null,
    selectedChannel: null,
    wizard: { phase: "idle" },
    wizardMultiselect: [],
    wizardTextValue: "",
    wizardSecretVisible: false,
    setupBlockedByDirtyConfig: false,
    onShowDetail: () => {},
    onCloseDetail: () => {},
    onStartSetup: () => {},
    onWizardAnswer: () => {},
    onWizardToggleMultiselect: () => {},
    onWizardTextInput: () => {},
    onWizardToggleSecretVisibility: () => {},
    onWizardClose: () => {},
    onRefresh: () => {},
    onPairingRefresh: () => {},
    onPairingFilterChange: () => {},
    onPairingReviewAccount: () => {},
    onPairingApprove: () => {},
    onPairingDismiss: () => {},
    onPairingPromptChange: () => {},
    onPairingPromptCancel: () => {},
    onPairingPromptConfirm: () => {},
    onWhatsAppStart: () => {},
    onWhatsAppWait: () => {},
    onWhatsAppLogout: () => {},
    onShowAdvancedSettings: () => {},
    onConfigPatch: () => {},
    onConfigSave: () => {},
    onConfigReload: () => {},
    onNostrProfileEdit: () => {},
    onNostrProfileCancel: () => {},
    onNostrProfileFieldChange: () => {},
    onNostrProfileSave: () => {},
    onNostrProfileImport: () => {},
    onNostrProfileToggleAdvanced: () => {},
    ...overrides,
  };
}
