import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { parse } from "yaml";
import {
  mobileReleasePlanDigest,
  writeMobileReleaseIntent,
} from "../../scripts/mobile-release-intent.mjs";
import { applyMobileReleasePlan, planMobileRelease } from "../../scripts/mobile-release-version.ts";
import { useAutoCleanupTempDirTracker } from "../helpers/temp-dir.js";

const REPOSITORY = "openclaw/openclaw";
const TARGET_REF = "release/2026.9.2-mobile";
const OTHER_SHA = "c".repeat(40);
const RECEIPT_ARTIFACT_DIGEST = `sha256:${"d".repeat(64)}`;
const INTENT_ARTIFACT_DIGEST = `sha256:${"e".repeat(64)}`;
const BUILD_TIMESTAMP = "2026-09-02T06:00:00.000Z";
const RELEASE_PATHS = [
  "apps/mobile/version.json",
  "apps/android/version.json",
  "apps/android/Config/Version.properties",
  "apps/android/fastlane/metadata/android/en-US/release_notes.txt",
  "apps/ios/CHANGELOG.md",
] as const;
const TOOLING_FILES = [
  "scripts/mobile-release-version.ts",
  "scripts/mobile-release-intent.mjs",
  "scripts/lib/android-version.ts",
  "scripts/lib/direct-run.mjs",
  "scripts/lib/ios-release-plan.ts",
  "scripts/lib/ios-version.ts",
  "scripts/lib/mobile-version.ts",
  "scripts/lib/release-version.mjs",
] as const;
const tempRoots = useAutoCleanupTempDirTracker(afterEach);

type Platform = "ios" | "android";

type Fixture = {
  actionPath: string;
  baseSha: string;
  env: NodeJS.ProcessEnv;
  gitLog: string;
  ghLog: string;
  outputPath: string;
  platform: Platform;
  runnerTemp: string;
  scriptPath: string;
  source: string;
  stateDir: string;
  targetSha: string;
  trusted: string;
  workspace: string;
  workflowFullRef: string;
  workflowPath: string;
};

type FixtureOptions = {
  baseState?: "android-current" | "prepared";
  beforeCandidate?: (repository: string) => void;
  buildCandidate?: (repository: string, baseSha: string) => string;
  emptyCandidate?: boolean;
  mutateBase?: (repository: string) => void;
  mutateCandidate?: (repository: string) => void;
  platform?: Platform;
  realFetch?: boolean;
};

function command(
  executable: string,
  args: string[],
  options: { cwd?: string; env?: NodeJS.ProcessEnv } = {},
) {
  const result = spawnSync(executable, args, {
    cwd: options.cwd,
    encoding: "utf8",
    env: options.env ?? process.env,
  });
  if (result.status !== 0) {
    throw new Error(`${executable} ${args.join(" ")} failed:\n${result.stdout}\n${result.stderr}`);
  }
  return result.stdout.trim();
}

function git(cwd: string, ...args: string[]): string {
  return command("/usr/bin/git", args, { cwd });
}

function writeFile(root: string, file: string, source: string): void {
  const destination = path.join(root, file);
  fs.mkdirSync(path.dirname(destination), { recursive: true });
  fs.writeFileSync(destination, source);
}

function copyFile(root: string, file: string): void {
  const destination = path.join(root, file);
  fs.mkdirSync(path.dirname(destination), { recursive: true });
  fs.copyFileSync(file, destination);
}

function commit(repository: string, message: string): string {
  git(repository, "add", "-A");
  git(repository, "commit", "-m", message);
  return git(repository, "rev-parse", "HEAD");
}

function emptyCommit(repository: string, message: string): string {
  git(repository, "commit", "--allow-empty", "-m", message);
  return git(repository, "rev-parse", "HEAD");
}

function writeBaseReleaseFiles(repository: string): void {
  writeFile(repository, "apps/mobile/version.json", '{\n  "version": "2026.9.1"\n}\n');
  writeFile(
    repository,
    "apps/android/version.json",
    '{\n  "version": "2026.9.1",\n  "versionCode": 2026090101\n}\n',
  );
  writeFile(
    repository,
    "apps/android/Config/Version.properties",
    [
      "# Shared Android version defaults.",
      "# Source of truth: apps/android/version.json",
      "# Generated by scripts/android-sync-versioning.ts.",
      "",
      "OPENCLAW_ANDROID_VERSION_NAME=2026.9.1",
      "OPENCLAW_ANDROID_VERSION_CODE=2026090101",
      "",
    ].join("\n"),
  );
  writeFile(
    repository,
    "apps/android/fastlane/metadata/android/en-US/release_notes.txt",
    "Previous mobile release.\n",
  );
  writeFile(
    repository,
    "apps/ios/CHANGELOG.md",
    [
      "# OpenClaw iOS Changelog",
      "",
      "## Unreleased",
      "",
      "- Adds guarded mobile beta automation.",
      "",
      "## 2026.9.10",
      "",
      "- Previous mobile release.",
      "",
    ].join("\n"),
  );
}

function createCandidate(repository: string): void {
  applyMobileReleasePlan(
    planMobileRelease({
      gatewayVersion: "2026.9.2",
      phase: "prepare",
      rootDir: repository,
    }),
  );
  applyMobileReleasePlan(
    planMobileRelease({
      gatewayVersion: "2026.9.2",
      iosPlan: {
        appStoreRevision: 0,
        appStoreVersion: "2026.9.20",
        appStoreVersionId: null,
        appStoreVersionState: null,
        buildNumber: 1,
        buildUploads: [],
        changelogStatus: "needs-cut",
        decision: "new-revision",
        gatewayVersion: "2026.9.2",
        sourceClean: true,
        sourceSha: null,
      },
      phase: "finalize",
      rootDir: repository,
    }),
  );
}

function writeGitShim(binDir: string, realFetch: boolean): void {
  const shim = path.join(binDir, "git");
  fs.writeFileSync(
    shim,
    `#!/usr/bin/env node
const fs = require("node:fs");
const { spawnSync } = require("node:child_process");
const args = process.argv.slice(2);
const gitArgs = args[0] === "-C" ? args.slice(2) : args;
fs.appendFileSync(process.env.GIT_LOG, JSON.stringify(args) + "\\n");
if (gitArgs[0] === "remote" && gitArgs[1] === "get-url") {
  process.stdout.write("https://github.com/openclaw/openclaw.git\\n");
  process.exit(0);
}
if (gitArgs[0] === "fetch" && !${JSON.stringify(realFetch)}) {
  process.exit(0);
}
const result = spawnSync("/usr/bin/git", args, { stdio: "inherit" });
process.exit(result.status ?? 1);
`,
    { mode: 0o755 },
  );
}

function writeGhShim(binDir: string): void {
  const shim = path.join(binDir, "gh");
  fs.writeFileSync(
    shim,
    `#!/usr/bin/env node
const fs = require("node:fs");
const path = require("node:path");
const args = process.argv.slice(2);
fs.appendFileSync(process.env.GH_LOG, JSON.stringify({
  args,
  token: process.env.GH_TOKEN || ""
}) + "\\n");

function increment(name) {
  const file = path.join(process.env.GH_STATE_DIR, name);
  const index = fs.existsSync(file) ? Number(fs.readFileSync(file, "utf8")) : 0;
  fs.writeFileSync(file, String(index + 1));
  return index;
}

function next(name, fallback) {
  const values = (process.env[name] || fallback).split(",");
  const index = increment(name);
  return values[Math.min(index, values.length - 1)];
}

if (args[0] === "attestation" && args[1] === "verify") {
  process.exit(Number(process.env.GH_ATTESTATION_EXIT || "0"));
}
if (args[0] !== "api") {
  console.error("unexpected gh invocation", JSON.stringify(args));
  process.exit(70);
}
const endpoint = args[1] || "";
if (endpoint.includes("/collaborators/")) {
  process.stdout.write(next("GH_PERMISSIONS", process.env.GH_PERMISSION || "write") + "\\n");
} else if (endpoint.includes("/actions/runs/") && endpoint.includes("/attempts/")) {
  const runId = endpoint.match(/\\/actions\\/runs\\/(\\d+)\\//)[1];
  const isCurrent = runId === process.env.GITHUB_RUN_ID;
  const actor = isCurrent ? process.env.GITHUB_ACTOR : process.env.MOBILE_ACTOR;
  const triggeringActor = isCurrent
    ? process.env.GITHUB_TRIGGERING_ACTOR
    : process.env.MOBILE_TRIGGERING_ACTOR;
  const currentCancelled = path.join(process.env.GH_STATE_DIR, "GH_CURRENT_CANCELLED");
  const cancelled = isCurrent && fs.existsSync(currentCancelled);
  const status = cancelled
    ? "completed"
    : isCurrent
    ? next("GH_CURRENT_STATUSES", process.env.GH_CURRENT_STATUS || "in_progress")
    : next("GH_ORIGINAL_STATUSES", process.env.GH_ORIGINAL_STATUS || "in_progress");
  const conclusion = cancelled
    ? "cancelled"
    : JSON.parse(isCurrent
      ? next("GH_CURRENT_CONCLUSIONS", process.env.GH_CURRENT_CONCLUSION || "null")
      : next("GH_ORIGINAL_CONCLUSIONS", process.env.GH_ORIGINAL_CONCLUSION || "null"));
  const runAttempt = Number(isCurrent
    ? next("GH_CURRENT_ATTEMPTS", "1")
    : next("GH_ORIGINAL_ATTEMPTS", "1"));
  if (!isCurrent) {
    const originalRead = increment("GH_ORIGINAL_LIFECYCLE_READS") + 1;
    if (originalRead === Number(process.env.GH_CANCEL_CURRENT_AFTER_ORIGINAL_READ || "0")) {
      fs.writeFileSync(currentCancelled, "1");
    }
  }
  process.stdout.write(JSON.stringify({
    actor: { login: actor },
    conclusion,
    event: "workflow_dispatch",
    head_branch: "main",
    head_sha: isCurrent ? process.env.MOBILE_WORKFLOW_SHA : process.env.GH_ORIGINAL_WORKFLOW_SHA,
    id: Number(runId),
    path: process.env.MOBILE_WORKFLOW_PATH + "@refs/heads/main",
    run_attempt: runAttempt,
    run_started_at: ${JSON.stringify(BUILD_TIMESTAMP)},
    status,
    triggering_actor: { login: triggeringActor }
  }) + "\\n");
} else if (endpoint.includes("/actions/runs/") && endpoint.includes("/artifacts")) {
  const artifacts = [];
  if (process.env.MOBILE_RECEIPT_ARTIFACT_ID) {
    artifacts.push({
      digest: process.env.MOBILE_RECEIPT_ARTIFACT_DIGEST,
      expired: false,
      id: Number(process.env.MOBILE_RECEIPT_ARTIFACT_ID),
      name: process.env.MOBILE_RECEIPT_ARTIFACT_NAME,
      workflow_run: { id: Number(process.env.MOBILE_AUTHORITY_RUN_ID) }
    });
  }
  if (process.env.MOBILE_INTENT_ARTIFACT_ID) {
    artifacts.push({
      digest: process.env.MOBILE_INTENT_ARTIFACT_DIGEST,
      expired: false,
      id: Number(process.env.MOBILE_INTENT_ARTIFACT_ID),
      name: process.env.MOBILE_INTENT_ARTIFACT_NAME,
      workflow_run: { id: Number(process.env.MOBILE_AUTHORITY_RUN_ID) }
    });
  }
  process.stdout.write(JSON.stringify({ artifacts }) + "\\n");
} else if (endpoint.includes("/actions/artifacts/")) {
  const receipt = endpoint.endsWith("/" + process.env.MOBILE_RECEIPT_ARTIFACT_ID);
  const runId = receipt
    ? (process.env.GH_RECEIPT_RUN_ID || process.env.MOBILE_AUTHORITY_RUN_ID)
    : (process.env.GH_INTENT_RUN_ID || process.env.MOBILE_AUTHORITY_RUN_ID);
  process.stdout.write(JSON.stringify({
    digest: receipt
      ? process.env.MOBILE_RECEIPT_ARTIFACT_DIGEST
      : process.env.MOBILE_INTENT_ARTIFACT_DIGEST,
    expired: false,
    id: Number(receipt
      ? process.env.MOBILE_RECEIPT_ARTIFACT_ID
      : process.env.MOBILE_INTENT_ARTIFACT_ID),
    name: receipt
      ? process.env.MOBILE_RECEIPT_ARTIFACT_NAME
      : process.env.MOBILE_INTENT_ARTIFACT_NAME,
    workflow_run: { id: Number(runId) }
  }) + "\\n");
} else if (endpoint.includes("/git/ref/heads/main")) {
  process.stdout.write(next("GH_MAIN_REFS", process.env.MOBILE_WORKFLOW_SHA) + "\\n");
} else if (endpoint.includes("/git/ref/heads/release/")) {
  process.stdout.write(next("GH_TARGET_REFS", process.env.MOBILE_TARGET_SHA) + "\\n");
} else if (endpoint.includes("/git/ref/openclaw/mobile-releases/")) {
  const file = path.join(process.env.GH_STATE_DIR, "release-ref");
  if (!fs.existsSync(file)) process.exit(1);
  process.stdout.write(fs.readFileSync(file, "utf8") + "\\n");
} else if (endpoint.endsWith("/git/refs") && args.includes("POST")) {
  const sha = args.find((value) => value.startsWith("sha=")).slice(4);
  const file = path.join(process.env.GH_STATE_DIR, "release-ref");
  if (process.env.GH_CREATE_RACE === "1") {
    fs.writeFileSync(file, process.env.MOBILE_TARGET_SHA);
    process.exit(1);
  }
  if (process.env.GH_CREATE_FAIL === "1") process.exit(1);
  fs.writeFileSync(file, sha);
  process.stdout.write("{}\\n");
} else {
  console.error("unexpected gh endpoint", endpoint);
  process.exit(71);
}
`,
    { mode: 0o755 },
  );
}

function createFixture(options: FixtureOptions = {}): Fixture {
  const platform = options.platform ?? "ios";
  const root = tempRoots.make("openclaw-mobile-release-authority-");
  const source = path.join(root, "source");
  const trusted = path.join(root, "trusted");
  const workspace = path.join(root, "workspace");
  const runnerTemp = path.join(root, "runner");
  const stateDir = path.join(root, "state");
  const binDir = path.join(root, "bin");
  const outputPath = path.join(root, "output");
  fs.mkdirSync(source);
  fs.mkdirSync(runnerTemp);
  fs.mkdirSync(stateDir);
  fs.mkdirSync(binDir);
  fs.writeFileSync(outputPath, "");

  git(source, "init", "-b", "main");
  git(source, "config", "user.email", "ci@example.invalid");
  git(source, "config", "user.name", "Mobile Release Test");
  for (const file of TOOLING_FILES) {
    copyFile(source, file);
  }
  copyFile(source, ".github/actions/mobile-release-authority/authority.mjs");
  writeFile(source, `.github/workflows/${platform}-beta-release.yml`, "name: fixture\n");
  writeBaseReleaseFiles(source);
  if (options.baseState === "android-current") {
    writeFile(
      source,
      "apps/android/version.json",
      '{\n  "version": "2026.9.2",\n  "versionCode": 2026090201\n}\n',
    );
  } else if (options.baseState === "prepared") {
    applyMobileReleasePlan(
      planMobileRelease({
        gatewayVersion: "2026.9.2",
        phase: "prepare",
        rootDir: source,
      }),
    );
  }
  options.mutateBase?.(source);
  const baseSha = commit(source, "base");
  options.beforeCandidate?.(source);

  let targetSha: string;
  if (options.buildCandidate) {
    targetSha = options.buildCandidate(source, baseSha);
  } else if (options.emptyCandidate) {
    targetSha = emptyCommit(source, "candidate");
  } else {
    createCandidate(source);
    options.mutateCandidate?.(source);
    targetSha = commit(source, "candidate");
  }

  if (options.realFetch) {
    git(source, "branch", TARGET_REF, targetSha);
    git(source, "reset", "--hard", baseSha);
  }
  git(
    root,
    "clone",
    "--no-local",
    ...(options.realFetch ? ["--single-branch", "--branch", "main"] : []),
    source,
    trusted,
  );
  git(trusted, "checkout", "--detach", baseSha);
  git(trusted, "update-ref", "refs/remotes/origin/mobile-authority-main", baseSha);
  if (!options.realFetch) {
    git(trusted, "update-ref", "refs/remotes/origin/mobile-authority-target", targetSha);
  }
  git(
    root,
    "clone",
    "--no-local",
    ...(options.realFetch ? ["--branch", TARGET_REF] : []),
    source,
    workspace,
  );
  git(workspace, "checkout", "--detach", targetSha);

  writeGitShim(binDir, options.realFetch === true);
  writeGhShim(binDir);
  const actionPath = path.join(trusted, ".github/actions/mobile-release-authority");
  const workflowPath = `.github/workflows/${platform}-beta-release.yml`;
  const workflowFullRef = `${REPOSITORY}/${workflowPath}@refs/heads/main`;
  const gitLog = path.join(root, "git.log");
  const ghLog = path.join(root, "gh.log");
  fs.writeFileSync(gitLog, "");
  fs.writeFileSync(ghLog, "");

  const env: NodeJS.ProcessEnv = {
    ...process.env,
    PATH: `${binDir}${path.delimiter}${process.env.PATH ?? ""}`,
    GIT_LOG: gitLog,
    GH_TOKEN: "",
    GH_LOG: ghLog,
    GH_MAIN_REFS: `${baseSha},${baseSha},${baseSha},${baseSha}`,
    GH_ORIGINAL_WORKFLOW_SHA: baseSha,
    GH_STATE_DIR: stateDir,
    GH_TARGET_REFS: `${targetSha},${targetSha},${targetSha},${targetSha}`,
    GITHUB_ACTOR: "release-owner",
    GITHUB_EVENT_NAME: "workflow_dispatch",
    GITHUB_OUTPUT: outputPath,
    GITHUB_REF: "refs/heads/main",
    GITHUB_REPOSITORY: REPOSITORY,
    GITHUB_RUN_ATTEMPT: "1",
    GITHUB_RUN_ID: "123",
    GITHUB_SHA: baseSha,
    GITHUB_TRIGGERING_ACTOR: "release-owner",
    GITHUB_WORKFLOW_REF: workflowFullRef,
    GITHUB_WORKSPACE: workspace,
    MOBILE_ACTION_PATH: actionPath,
    MOBILE_ACTOR: "release-owner",
    MOBILE_AUTHORITY_RUN_ID: "123",
    MOBILE_OPERATION: "authorize",
    MOBILE_PLATFORM: platform,
    MOBILE_RECOVERY: "false",
    MOBILE_RELEASE_REF_TOKEN: "",
    MOBILE_TARGET_REF: TARGET_REF,
    MOBILE_TARGET_SHA: targetSha,
    MOBILE_TRIGGERING_ACTOR: "release-owner",
    MOBILE_WORKFLOW_FULL_REF: workflowFullRef,
    MOBILE_WORKFLOW_PATH: workflowPath,
    MOBILE_WORKFLOW_SHA: baseSha,
    RUNNER_TEMP: runnerTemp,
  };

  return {
    actionPath,
    baseSha,
    env,
    gitLog,
    ghLog,
    outputPath,
    platform,
    runnerTemp,
    scriptPath: path.join(actionPath, "authority.mjs"),
    source,
    stateDir,
    targetSha,
    trusted,
    workspace,
    workflowFullRef,
    workflowPath,
  };
}

function useTrustedWorkflow(fixture: Fixture, workflowSha: string): void {
  git(fixture.trusted, "fetch", "origin", workflowSha);
  git(fixture.trusted, "checkout", "--detach", workflowSha);
  git(fixture.trusted, "update-ref", "refs/remotes/origin/mobile-authority-main", workflowSha);
  Object.assign(fixture.env, {
    GH_MAIN_REFS: `${workflowSha},${workflowSha},${workflowSha},${workflowSha}`,
    GH_ORIGINAL_WORKFLOW_SHA: workflowSha,
    GITHUB_SHA: workflowSha,
    MOBILE_WORKFLOW_SHA: workflowSha,
  });
}

function advanceTrustedTooling(
  fixture: Fixture,
  options: {
    fromSha?: string;
    mutate?: (repository: string) => void;
  } = {},
): string {
  git(
    fixture.source,
    "checkout",
    "-b",
    "trusted-main-after-code-freeze",
    options.fromSha ?? fixture.baseSha,
  );
  options.mutate?.(fixture.source);
  const workflowSha = git(fixture.source, "status", "--porcelain")
    ? commit(fixture.source, "advance trusted release tooling")
    : emptyCommit(fixture.source, "advance trusted release tooling");
  useTrustedWorkflow(fixture, workflowSha);
  return workflowSha;
}

function runAuthority(fixture: Fixture, phase: string, overrides: NodeJS.ProcessEnv = {}) {
  fs.writeFileSync(fixture.outputPath, "");
  return spawnSync(process.execPath, ["--experimental-strip-types", fixture.scriptPath, phase], {
    encoding: "utf8",
    env: { ...fixture.env, ...overrides },
  });
}

function readOutputs(file: string): Record<string, string> {
  return Object.fromEntries(
    fs
      .readFileSync(file, "utf8")
      .trim()
      .split("\n")
      .filter(Boolean)
      .map((line) => {
        const separator = line.indexOf("=");
        return [line.slice(0, separator), line.slice(separator + 1)];
      }),
  );
}

function readGhTrace(file: string): Array<{ args: string[]; token: string }> {
  return fs
    .readFileSync(file, "utf8")
    .trim()
    .split("\n")
    .filter(Boolean)
    .map((line) => JSON.parse(line) as { args: string[]; token: string });
}

function resetState(fixture: Fixture): void {
  fs.rmSync(fixture.stateDir, { recursive: true, force: true });
  fs.mkdirSync(fixture.stateDir);
  fs.writeFileSync(fixture.ghLog, "");
}

function authorize(fixture: Fixture): Record<string, string> {
  const result = runAuthority(fixture, "authorize");
  expect(result.status, result.stderr).toBe(0);
  return readOutputs(fixture.outputPath);
}

function receiptOverrides(outputs: Record<string, string>): NodeJS.ProcessEnv {
  return {
    MOBILE_OPERATION: "revalidate",
    MOBILE_RECEIPT_ARTIFACT_DIGEST: RECEIPT_ARTIFACT_DIGEST,
    MOBILE_RECEIPT_ARTIFACT_ID: "456",
    MOBILE_RECEIPT_ARTIFACT_NAME: outputs.artifact_name,
  };
}

function signIntentFile(fixture: Fixture, outputs: Record<string, string>): void {
  const destination = path.join(
    fixture.runnerTemp,
    `mobile-release-intent-${fixture.platform}`,
    "intent.json",
  );
  const common = {
    authorityReceiptDigest: outputs.receipt_digest,
    gatewayVersion: "2026.9.2",
    kind: "openclaw-mobile-release-ref-intent",
    platform: fixture.platform,
    schemaVersion: 2,
    targetRef: TARGET_REF,
    targetSha: fixture.targetSha,
  };
  const unsigned =
    fixture.platform === "ios"
      ? {
          ...common,
          appStoreVersion: "2026.9.20",
          buildNumber: "8",
          internalGroupId: "group-123",
          internalGroupName: "OpenClaw Internal",
        }
      : {
          ...common,
          phoneTrack: "internal",
          phoneVersionCode: "2026090201",
          playEditState: "committed",
          releaseStatus: "completed",
          versionName: "2026.9.2",
          wearTrack: "wear:internal",
          wearVersionCode: "2026090251",
        };
  writeMobileReleaseIntent(destination, {
    ...unsigned,
    planDigest: mobileReleasePlanDigest(unsigned),
  });
}

function recordOverrides(fixture: Fixture, outputs: Record<string, string>): NodeJS.ProcessEnv {
  return {
    ...receiptOverrides(outputs),
    MOBILE_INTENT_ARTIFACT_DIGEST: INTENT_ARTIFACT_DIGEST,
    MOBILE_INTENT_ARTIFACT_ID: "789",
    MOBILE_INTENT_ARTIFACT_NAME: `mobile-release-intent-${fixture.platform}-123-1`,
    MOBILE_OPERATION: "record",
  };
}

function prepareRecoveryOverrides(
  fixture: Fixture,
  outputs: Record<string, string>,
): NodeJS.ProcessEnv {
  git(fixture.source, "checkout", "-b", "trusted-main-after-upload", fixture.baseSha);
  git(fixture.source, "commit", "--allow-empty", "-m", "advance trusted main after upload");
  const recoveryWorkflowSha = git(fixture.source, "rev-parse", "HEAD");
  git(fixture.trusted, "fetch", "origin", recoveryWorkflowSha);
  git(fixture.trusted, "checkout", "--detach", recoveryWorkflowSha);
  return {
    ...recordOverrides(fixture, outputs),
    GH_ORIGINAL_CONCLUSION: '"failure"',
    GH_ORIGINAL_STATUS: "completed",
    GH_MAIN_REFS: `${recoveryWorkflowSha},${recoveryWorkflowSha}`,
    GITHUB_RUN_ID: "999",
    GITHUB_SHA: recoveryWorkflowSha,
    MOBILE_RECOVERY: "true",
    MOBILE_WORKFLOW_SHA: recoveryWorkflowSha,
  };
}

function expectOnlyAttemptOneLifecycleReads(
  trace: Array<{ args: string[]; token: string }>,
  expectedCount: number,
): void {
  const lifecycleReads = trace.filter(({ args }) => args[1]?.includes("/actions/runs/"));
  expect(lifecycleReads).toHaveLength(expectedCount);
  expect(lifecycleReads.every(({ args }) => args[1]?.endsWith("/attempts/1"))).toBe(true);
}

describe("mobile release authority", () => {
  it("authorizes an exact five-file release candidate and emits an attested v2 receipt", () => {
    const fixture = createFixture();
    const outputs = authorize(fixture);
    const receipt = JSON.parse(
      fs.readFileSync(path.join(fixture.runnerTemp, "mobile-release-ref-ios/receipt.json"), "utf8"),
    ) as Record<string, unknown>;

    expect(outputs).toMatchObject({
      approved: "true",
      gateway_version: "2026.9.2",
      target_ref: TARGET_REF,
      target_sha: fixture.targetSha,
    });
    expect(receipt).toMatchObject({
      androidPhoneVersionCode: "2026090201",
      androidVersionName: "2026.9.2",
      androidWearVersionCode: "2026090251",
      gatewayVersion: "2026.9.2",
      iosAppStoreVersion: "2026.9.20",
      kind: "openclaw-mobile-release-authority",
      schemaVersion: 2,
      targetRef: TARGET_REF,
      targetSha: fixture.targetSha,
      workflowSha: fixture.baseSha,
    });

    resetState(fixture);
    const sink = runAuthority(fixture, "revalidate", receiptOverrides(outputs));
    expect(sink.status, sink.stderr).toBe(0);
    expect(fs.readFileSync(fixture.ghLog, "utf8")).toContain(
      `"--source-digest","${fixture.baseSha}"`,
    );
  });

  it.each([
    [
      "four-file",
      "android-current",
      RELEASE_PATHS.filter((file) => file !== "apps/android/version.json").toSorted(),
    ],
    ["one-file", "prepared", ["apps/ios/CHANGELOG.md"]],
  ] as const)(
    "authorizes a cutter-exact %s release candidate",
    (_label, baseState, expectedPaths) => {
      const fixture = createFixture({ baseState });
      const changedPaths = git(
        fixture.source,
        "diff",
        "--name-only",
        fixture.baseSha,
        fixture.targetSha,
      ).split("\n");

      expect(changedPaths).toEqual(expectedPaths);
      expect(authorize(fixture)).toMatchObject({
        approved: "true",
        gateway_version: "2026.9.2",
        target_ref: TARGET_REF,
        target_sha: fixture.targetSha,
      });
    },
  );

  it("authorizes a metadata-only candidate frozen before trusted tooling advances", () => {
    const fixture = createFixture();
    const workflowSha = advanceTrustedTooling(fixture);

    const outputs = authorize(fixture);
    const receipt = JSON.parse(
      fs.readFileSync(path.join(fixture.runnerTemp, "mobile-release-ref-ios/receipt.json"), "utf8"),
    ) as Record<string, unknown>;

    expect(outputs.target_sha).toBe(fixture.targetSha);
    expect(receipt.workflowSha).toBe(workflowSha);
  });

  it("regenerates from Code SHA metadata with the newer Tooling SHA", () => {
    const fixture = createFixture();
    advanceTrustedTooling(fixture, {
      mutate(repository) {
        writeFile(
          repository,
          "apps/ios/CHANGELOG.md",
          fs
            .readFileSync(path.join(repository, "apps/ios/CHANGELOG.md"), "utf8")
            .replace("Adds guarded mobile beta automation.", "Tooling-only unreleased note."),
        );
      },
    });

    expect(authorize(fixture).target_sha).toBe(fixture.targetSha);
  });

  it("uses the Tooling SHA cutter implementation with the Code SHA baseline", () => {
    const fixture = createFixture({
      mutateBase(repository) {
        writeFile(repository, "scripts/mobile-release-version.ts", 'throw new Error("stale");\n');
      },
    });
    advanceTrustedTooling(fixture, {
      mutate(repository) {
        copyFile(repository, "scripts/mobile-release-version.ts");
      },
    });

    expect(authorize(fixture).target_sha).toBe(fixture.targetSha);
  });

  it("rejects a forbidden code commit hidden by a later revert", () => {
    const fixture = createFixture({
      beforeCandidate(repository) {
        writeFile(repository, "scripts/forged-upload.sh", "forged\n");
        commit(repository, "add forbidden release code");
        fs.rmSync(path.join(repository, "scripts/forged-upload.sh"));
        commit(repository, "revert forbidden release code");
      },
    });

    const result = runAuthority(fixture, "authorize");

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("non-metadata or non-regular change");
  });

  it.each([
    ["multiple metadata commits", false],
    ["an empty intermediate commit", true],
  ] as const)("authorizes a candidate with %s", (_label, includeEmptyCommit) => {
    const fixture = createFixture({
      buildCandidate(repository) {
        writeFile(
          repository,
          "apps/android/fastlane/metadata/android/en-US/release_notes.txt",
          "Intermediate generated notes.\n",
        );
        commit(repository, "prepare generated metadata");
        if (includeEmptyCommit) {
          emptyCommit(repository, "record release checkpoint");
        }
        createCandidate(repository);
        return commit(repository, "finalize generated metadata");
      },
    });

    expect(authorize(fixture).target_sha).toBe(fixture.targetSha);
  });

  it("rejects a merge commit in the candidate suffix", () => {
    const fixture = createFixture({
      buildCandidate(repository, baseSha) {
        git(repository, "checkout", "-b", "candidate-side", baseSha);
        emptyCommit(repository, "candidate side");
        const sideSha = git(repository, "rev-parse", "HEAD");
        git(repository, "checkout", "-b", "candidate-main", baseSha);
        createCandidate(repository);
        commit(repository, "candidate metadata");
        git(repository, "merge", "--no-ff", "--no-edit", sideSha);
        return git(repository, "rev-parse", "HEAD");
      },
    });

    const result = runAuthority(fixture, "authorize");

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("bounded linear commit chain");
  });

  it("rejects an unrelated candidate history", () => {
    const fixture = createFixture({
      buildCandidate(repository, baseSha) {
        git(repository, "checkout", "--orphan", "unrelated-candidate");
        git(repository, "rm", "-r", "-f", "--quiet", ".");
        git(repository, "checkout", baseSha, "--", ".");
        commit(repository, "unrelated root");
        createCandidate(repository);
        return commit(repository, "unrelated candidate");
      },
    });

    const result = runAuthority(fixture, "authorize");

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("exactly one shared Code SHA");
  });

  it("rejects ambiguous Code SHA ancestry", () => {
    let toolingSha = "";
    const fixture = createFixture({
      buildCandidate(repository, baseSha) {
        git(repository, "checkout", "-b", "left", baseSha);
        const leftSha = emptyCommit(repository, "left");
        git(repository, "checkout", "-b", "right", baseSha);
        const rightSha = emptyCommit(repository, "right");
        git(repository, "checkout", "left");
        git(repository, "merge", "--no-ff", "--no-edit", rightSha);
        toolingSha = git(repository, "rev-parse", "HEAD");
        git(repository, "checkout", "-b", "candidate-criss-cross", rightSha);
        git(repository, "merge", "--no-ff", "--no-edit", leftSha);
        createCandidate(repository);
        return commit(repository, "candidate after criss-cross");
      },
    });
    useTrustedWorkflow(fixture, toolingSha);

    const result = runAuthority(fixture, "authorize");

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("exactly one shared Code SHA");
  });

  it("rejects a Code SHA reachable only through Tooling SHA second-parent history", () => {
    let codeSha = "";
    const fixture = createFixture({
      buildCandidate(repository) {
        codeSha = emptyCommit(repository, "code branch");
        createCandidate(repository);
        return commit(repository, "candidate metadata");
      },
    });
    git(fixture.source, "checkout", "-b", "trusted-first-parent", fixture.baseSha);
    emptyCommit(fixture.source, "trusted first parent");
    git(fixture.source, "merge", "--no-ff", "--no-edit", codeSha);
    useTrustedWorkflow(fixture, git(fixture.source, "rev-parse", "HEAD"));

    const result = runAuthority(fixture, "authorize");

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("first-parent history");
  });

  it("rejects a target equal to the derived Code SHA", () => {
    const fixture = createFixture();
    advanceTrustedTooling(fixture, { fromSha: fixture.targetSha });

    const result = runAuthority(fixture, "authorize");

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("at least one commit after its Code SHA");
  });

  it("rejects a candidate suffix longer than 32 commits", () => {
    const fixture = createFixture({
      buildCandidate(repository) {
        for (let index = 0; index < 32; index += 1) {
          emptyCommit(repository, `candidate checkpoint ${index + 1}`);
        }
        createCandidate(repository);
        return commit(repository, "candidate metadata");
      },
      realFetch: true,
    });

    expect(
      git(fixture.source, "rev-list", "--count", `${fixture.baseSha}..${fixture.targetSha}`),
    ).toBe("33");
    const result = runAuthority(fixture, "authorize");

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("exactly one shared Code SHA");
  });

  it("fetches enough real candidate history to authorize exactly 32 commits", () => {
    const fixture = createFixture({
      buildCandidate(repository) {
        for (let index = 0; index < 31; index += 1) {
          emptyCommit(repository, `candidate checkpoint ${index + 1}`);
        }
        createCandidate(repository);
        return commit(repository, "candidate metadata");
      },
      realFetch: true,
    });

    expect(
      git(fixture.source, "rev-list", "--count", `${fixture.baseSha}..${fixture.targetSha}`),
    ).toBe("32");
    expect(authorize(fixture).target_sha).toBe(fixture.targetSha);
    const fetches = fs
      .readFileSync(fixture.gitLog, "utf8")
      .trim()
      .split("\n")
      .map((line) => JSON.parse(line) as string[])
      .filter((args) => args.includes("fetch"));
    expect(fetches).toContainEqual([
      "-C",
      fixture.trusted,
      "fetch",
      "--no-tags",
      "--no-recurse-submodules",
      "--depth=33",
      "origin",
      `+refs/heads/${TARGET_REF}:refs/remotes/origin/mobile-authority-target`,
    ]);
  });

  it("rejects an empty release candidate", () => {
    const fixture = createFixture({ emptyCandidate: true });
    const result = runAuthority(fixture, "authorize");

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("raw diff is empty or malformed");
  });

  it.each([
    "release/2026.9.2",
    "release/2026.9.2-mobile-extra",
    "v2026.9.2-mobile",
    "refs/tags/v2026.9.2-mobile",
  ])("rejects noncanonical mobile release ref %s", (targetRef) => {
    const fixture = createFixture();
    const result = runAuthority(fixture, "authorize", { MOBILE_TARGET_REF: targetRef });

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("release/YYYY.M.PATCH-mobile");
  });

  it("rejects arbitrary SHAs and refs that move during authorization", () => {
    const fixture = createFixture();
    const arbitrary = runAuthority(fixture, "authorize", {
      GH_TARGET_REFS: `${OTHER_SHA},${OTHER_SHA}`,
    });
    expect(arbitrary.status).toBe(1);
    expect(arbitrary.stderr).toContain("approved target SHA");

    resetState(fixture);
    const moved = runAuthority(fixture, "authorize", {
      GH_TARGET_REFS: `${fixture.targetSha},${OTHER_SHA}`,
    });
    expect(moved.status).toBe(1);
    expect(moved.stderr).toContain("changed during authority validation");
  });

  it.each([
    ["workflow ref", { GITHUB_WORKFLOW_REF: `${REPOSITORY}/other.yml@refs/heads/main` }],
    ["workflow SHA", { GITHUB_SHA: OTHER_SHA }],
    ["run attempt", { GITHUB_RUN_ATTEMPT: "2" }],
  ])("rejects the wrong %s before candidate authorization", (_label, overrides) => {
    const fixture = createFixture();
    const result = runAuthority(fixture, "authorize", overrides);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("original canonical main workflow dispatch");
  });

  it("rejects a read-only dispatcher before release or sink authority is reachable", () => {
    const fixture = createFixture();
    const result = runAuthority(fixture, "authorize", { GH_PERMISSION: "read" });

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("lacks write, maintain, or admin permission");
    expect(readGhTrace(fixture.ghLog)).toEqual([
      {
        args: ["api", `repos/${REPOSITORY}/actions/runs/123/attempts/1`],
        token: "",
      },
      {
        args: [
          "api",
          `repos/${REPOSITORY}/collaborators/release-owner/permission`,
          "--jq",
          ".permission",
        ],
        token: "",
      },
    ]);
    expect(fs.readFileSync(fixture.outputPath, "utf8")).toBe("");
    expect(fs.existsSync(path.join(fixture.runnerTemp, "mobile-release-ref-ios"))).toBe(false);
  });

  it.each([
    ["Fastfile", "apps/ios/fastlane/Fastfile"],
    ["package command", "package.json"],
    ["workflow", ".github/workflows/other.yml"],
    ["build logic", "apps/android/app/build.gradle.kts"],
    ["script", "scripts/forged-upload.sh"],
  ])("rejects target-controlled %s changes", (_label, file) => {
    const fixture = createFixture({
      mutateCandidate(repository) {
        writeFile(repository, file, "forged\n");
      },
    });
    const result = runAuthority(fixture, "authorize");

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("non-metadata or non-regular change");
  });

  it("rejects deletion, rename, executable mode, and symlink changes", () => {
    const mutations: Array<(repository: string) => void> = [
      (repository) => fs.rmSync(path.join(repository, RELEASE_PATHS[3])),
      (repository) =>
        fs.renameSync(
          path.join(repository, RELEASE_PATHS[3]),
          path.join(repository, `${RELEASE_PATHS[3]}.moved`),
        ),
      (repository) => fs.chmodSync(path.join(repository, RELEASE_PATHS[3]), 0o755),
      (repository) => {
        fs.rmSync(path.join(repository, RELEASE_PATHS[3]));
        fs.symlinkSync("release_notes.other", path.join(repository, RELEASE_PATHS[3]));
      },
    ];

    for (const mutateCandidate of mutations) {
      const fixture = createFixture({ mutateCandidate });
      const result = runAuthority(fixture, "authorize");
      expect(result.status).toBe(1);
      expect(result.stderr).toMatch(/non-metadata|regular non-executable|five generated/u);
    }
  });

  it("rejects malformed or cutter-divergent allowed metadata", () => {
    const fixture = createFixture({
      mutateCandidate(repository) {
        writeFile(
          repository,
          "apps/android/version.json",
          '{\n  "version": "2026.9.2",\n  "versionCode": 2026090202\n}\n',
        );
      },
    });
    const result = runAuthority(fixture, "authorize");

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("byte-match one trusted five-file cutter plan");
  });

  it("allows main to advance after authorization but rejects target movement and checkout drift", () => {
    const fixture = createFixture();
    const outputs = authorize(fixture);
    resetState(fixture);
    const mainAdvanced = runAuthority(fixture, "revalidate", {
      ...receiptOverrides(outputs),
      GH_MAIN_REFS: `${OTHER_SHA},${OTHER_SHA}`,
    });
    expect(mainAdvanced.status, mainAdvanced.stderr).toBe(0);

    resetState(fixture);
    const targetMoved = runAuthority(fixture, "revalidate", {
      ...receiptOverrides(outputs),
      GH_TARGET_REFS: `${fixture.targetSha},${OTHER_SHA}`,
    });
    expect(targetMoved.status).toBe(1);
    expect(targetMoved.stderr).toContain("changed during authority validation");

    resetState(fixture);
    fs.writeFileSync(path.join(fixture.workspace, "apps/ios/CHANGELOG.md"), "dirty\n");
    const dirty = runAuthority(fixture, "revalidate", receiptOverrides(outputs));
    expect(dirty.status).toBe(1);
    expect(dirty.stderr).toContain("tracked changes");
  });

  it("rejects cancellation after candidate authorization before receipt output", () => {
    const fixture = createFixture();
    const result = runAuthority(fixture, "authorize", {
      GH_CURRENT_CONCLUSIONS: 'null,"cancelled"',
      GH_CURRENT_STATUSES: "in_progress,completed",
    });
    const trace = readGhTrace(fixture.ghLog);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("run identity is not exact");
    expectOnlyAttemptOneLifecycleReads(trace, 2);
    expect(fs.readFileSync(fixture.outputPath, "utf8")).toBe("");
    expect(fs.existsSync(path.join(fixture.runnerTemp, "mobile-release-ref-ios"))).toBe(false);
    expect(trace.some(({ args }) => args.includes("POST"))).toBe(false);
  });

  it("rejects cancellation after upload validation before success output", () => {
    const fixture = createFixture();
    const outputs = authorize(fixture);
    resetState(fixture);
    const result = runAuthority(fixture, "revalidate", {
      ...receiptOverrides(outputs),
      GH_CURRENT_CONCLUSIONS: 'null,null,"cancelled"',
      GH_CURRENT_STATUSES: "in_progress,in_progress,completed",
    });
    const trace = readGhTrace(fixture.ghLog);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("run identity is not exact");
    expectOnlyAttemptOneLifecycleReads(trace, 3);
    expect(fs.readFileSync(fixture.outputPath, "utf8")).toBe("");
    expect(trace.some(({ args }) => args.includes("POST"))).toBe(false);
  });

  it("rejects run-attempt drift after upload validation", () => {
    const fixture = createFixture();
    const outputs = authorize(fixture);
    resetState(fixture);
    const result = runAuthority(fixture, "revalidate", {
      ...receiptOverrides(outputs),
      GH_CURRENT_ATTEMPTS: "1,1,2",
    });
    const trace = readGhTrace(fixture.ghLog);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("run identity is not exact");
    expectOnlyAttemptOneLifecycleReads(trace, 3);
    expect(fs.readFileSync(fixture.outputPath, "utf8")).toBe("");
    expect(trace.some(({ args }) => args.includes("POST"))).toBe(false);
  });

  it("rejects cancellation before normal record authority returns", () => {
    const fixture = createFixture();
    const outputs = authorize(fixture);
    signIntentFile(fixture, outputs);
    resetState(fixture);
    const result = runAuthority(fixture, "validate-record", {
      ...recordOverrides(fixture, outputs),
      GH_CURRENT_CONCLUSIONS: 'null,null,"cancelled"',
      GH_CURRENT_STATUSES: "in_progress,in_progress,completed",
    });
    const trace = readGhTrace(fixture.ghLog);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("run identity is not exact");
    expectOnlyAttemptOneLifecycleReads(trace, 3);
    expect(fs.readFileSync(fixture.outputPath, "utf8")).toBe("");
    expect(trace.some(({ args }) => args.includes("POST"))).toBe(false);
  });

  it("rejects recovery cancellation and original-run drift before record authority returns", () => {
    const fixture = createFixture();
    const outputs = authorize(fixture);
    signIntentFile(fixture, outputs);
    const recovery = prepareRecoveryOverrides(fixture, outputs);

    resetState(fixture);
    const cancelled = runAuthority(fixture, "validate-record", {
      ...recovery,
      GH_CURRENT_CONCLUSIONS: 'null,null,"cancelled"',
      GH_CURRENT_STATUSES: "in_progress,in_progress,completed",
    });
    const cancelledTrace = readGhTrace(fixture.ghLog);
    expect(cancelled.status).toBe(1);
    expect(cancelled.stderr).toContain("run identity is not exact");
    expectOnlyAttemptOneLifecycleReads(cancelledTrace, 5);
    expect(fs.readFileSync(fixture.outputPath, "utf8")).toBe("");
    expect(cancelledTrace.some(({ args }) => args.includes("POST"))).toBe(false);

    resetState(fixture);
    const originalDrift = runAuthority(fixture, "validate-record", {
      ...recovery,
      GH_ORIGINAL_CONCLUSIONS: '"failure","success"',
    });
    const originalDriftTrace = readGhTrace(fixture.ghLog);
    expect(originalDrift.status).toBe(1);
    expect(originalDrift.stderr).toContain("run identity is not exact");
    expectOnlyAttemptOneLifecycleReads(originalDriftTrace, 4);
    expect(fs.readFileSync(fixture.outputPath, "utf8")).toBe("");
    expect(originalDriftTrace.some(({ args }) => args.includes("POST"))).toBe(false);
  });

  it("rejects cancellation immediately before immutable ref creation", () => {
    const fixture = createFixture();
    const outputs = authorize(fixture);
    signIntentFile(fixture, outputs);
    resetState(fixture);
    const result = runAuthority(fixture, "record", {
      ...recordOverrides(fixture, outputs),
      GH_CURRENT_CONCLUSIONS: 'null,null,null,"cancelled"',
      GH_CURRENT_STATUSES: "in_progress,in_progress,in_progress,completed",
      MOBILE_RELEASE_REF_TOKEN: "write-token",
    });
    const trace = readGhTrace(fixture.ghLog);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("run identity is not exact");
    expectOnlyAttemptOneLifecycleReads(trace, 4);
    expect(fs.readFileSync(fixture.outputPath, "utf8")).toBe("");
    expect(trace.some(({ args }) => args.includes("POST"))).toBe(false);
    expect(fs.existsSync(path.join(fixture.stateDir, "release-ref"))).toBe(false);
  });

  it("rechecks recovery lifecycle after the original-run read before ref creation", () => {
    const fixture = createFixture();
    const outputs = authorize(fixture);
    signIntentFile(fixture, outputs);
    const recovery = prepareRecoveryOverrides(fixture, outputs);
    resetState(fixture);
    const result = runAuthority(fixture, "record", {
      ...recovery,
      GH_CANCEL_CURRENT_AFTER_ORIGINAL_READ: "3",
      MOBILE_RELEASE_REF_TOKEN: "write-token",
    });
    const trace = readGhTrace(fixture.ghLog);
    const lifecycleReads = trace.filter(({ args }) => args[1]?.includes("/actions/runs/"));

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("run identity is not exact");
    expectOnlyAttemptOneLifecycleReads(trace, 7);
    expect(lifecycleReads.at(-1)?.args[1]).toContain("/actions/runs/999/attempts/1");
    expect(fs.readFileSync(fixture.outputPath, "utf8")).toBe("");
    expect(trace.some(({ args }) => args.includes("POST"))).toBe(false);
    expect(fs.existsSync(path.join(fixture.stateDir, "release-ref"))).toBe(false);
  });

  it("rejects permission revocation after upload candidate validation", () => {
    const fixture = createFixture();
    const outputs = authorize(fixture);
    resetState(fixture);
    const result = runAuthority(fixture, "revalidate", {
      ...receiptOverrides(outputs),
      GH_PERMISSIONS: "write,read",
    });
    const trace = readGhTrace(fixture.ghLog);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("lacks write, maintain, or admin permission");
    expect(fs.readFileSync(fixture.outputPath, "utf8")).toBe("");
    expect(trace.filter(({ args }) => args[1]?.includes("/collaborators/"))).toHaveLength(2);
    expect(trace.at(-1)?.args[1]).toContain("/collaborators/");
    expect(trace.some(({ args }) => args.includes("POST"))).toBe(false);
    expect(trace.every(({ token }) => token === "")).toBe(true);
  });

  it("rejects permission revocation after record validation before token-bearing ref work", () => {
    const fixture = createFixture();
    const outputs = authorize(fixture);
    signIntentFile(fixture, outputs);
    resetState(fixture);
    const result = runAuthority(fixture, "validate-record", {
      ...recordOverrides(fixture, outputs),
      GH_PERMISSIONS: "write,read",
    });
    const trace = readGhTrace(fixture.ghLog);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("lacks write, maintain, or admin permission");
    expect(fs.readFileSync(fixture.outputPath, "utf8")).toBe("");
    expect(trace.filter(({ args }) => args[1]?.includes("/collaborators/"))).toHaveLength(2);
    expect(trace.at(-1)?.args[1]).toContain("/collaborators/");
    expect(trace.some(({ args }) => args.includes("POST"))).toBe(false);
    expect(trace.every(({ token }) => token === "")).toBe(true);
  });

  it("rechecks permission after live ref reads immediately before immutable ref creation", () => {
    const fixture = createFixture();
    const outputs = authorize(fixture);
    signIntentFile(fixture, outputs);
    resetState(fixture);
    const result = runAuthority(fixture, "record", {
      ...recordOverrides(fixture, outputs),
      GH_PERMISSIONS: "write,write,read",
      MOBILE_RELEASE_REF_TOKEN: "write-token",
    });
    const trace = readGhTrace(fixture.ghLog);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("lacks write, maintain, or admin permission");
    expect(fs.readFileSync(fixture.outputPath, "utf8")).toBe("");
    expect(trace.filter(({ args }) => args[1]?.includes("/collaborators/"))).toHaveLength(3);
    expect(trace.some(({ args }) => args[1]?.includes("/git/ref/openclaw/mobile-releases/"))).toBe(
      true,
    );
    expect(trace.some(({ args }) => args[1]?.includes("/git/ref/heads/release/"))).toBe(true);
    expect(trace.at(-1)?.args[1]).toContain("/collaborators/");
    expect(trace.some(({ args }) => args.includes("POST"))).toBe(false);
    expect(fs.existsSync(path.join(fixture.stateDir, "release-ref"))).toBe(false);
  });

  it("records exact iOS and Android intents and handles an identical create race idempotently", () => {
    for (const platform of ["ios", "android"] as const) {
      const fixture = createFixture({ platform });
      const outputs = authorize(fixture);
      signIntentFile(fixture, outputs);
      resetState(fixture);
      const overrides = {
        ...recordOverrides(fixture, outputs),
        GH_CREATE_RACE: "1",
        MOBILE_RELEASE_REF_TOKEN: "write-token",
      };
      const validation = runAuthority(fixture, "validate-record", overrides);
      expect(validation.status, validation.stderr).toBe(0);
      const record = runAuthority(fixture, "record", overrides);
      expect(record.status, record.stderr).toBe(0);
      expect(readOutputs(fixture.outputPath)).toMatchObject({
        release_sha: fixture.targetSha,
      });
      expect(readOutputs(fixture.outputPath).release_ref).toBe(
        platform === "ios"
          ? "refs/openclaw/mobile-releases/ios/2026.9.20-8"
          : "refs/openclaw/mobile-releases/android/2026.9.2-2026090201",
      );
      expect(fs.readFileSync(fixture.ghLog, "utf8")).toContain('"token":"write-token"');
    }
  });

  it("rejects artifact replay, plan mismatch, moved authority, and conflicting immutable refs", () => {
    const fixture = createFixture();
    const outputs = authorize(fixture);
    signIntentFile(fixture, outputs);

    resetState(fixture);
    const replay = runAuthority(fixture, "validate-record", {
      ...recordOverrides(fixture, outputs),
      GH_INTENT_RUN_ID: "999",
    });
    expect(replay.status).toBe(1);
    expect(replay.stderr).toContain("artifact metadata");

    resetState(fixture);
    const intentPath = path.join(fixture.runnerTemp, "mobile-release-intent-ios/intent.json");
    const intent = JSON.parse(fs.readFileSync(intentPath, "utf8")) as Record<string, unknown>;
    intent.planDigest = `sha256:${"f".repeat(64)}`;
    fs.writeFileSync(intentPath, `${JSON.stringify(intent)}\n`);
    const mismatched = runAuthority(fixture, "validate-record", recordOverrides(fixture, outputs));
    expect(mismatched.status).toBe(1);
    expect(mismatched.stderr).toContain("plan digest");

    signIntentFile(fixture, outputs);
    resetState(fixture);
    const moved = runAuthority(fixture, "validate-record", {
      ...recordOverrides(fixture, outputs),
      GH_TARGET_REFS: `${fixture.targetSha},${OTHER_SHA}`,
    });
    expect(moved.status).toBe(1);
    expect(moved.stderr).toContain("changed during authority validation");

    resetState(fixture);
    fs.writeFileSync(path.join(fixture.stateDir, "release-ref"), OTHER_SHA);
    const conflict = runAuthority(fixture, "record", {
      ...recordOverrides(fixture, outputs),
      MOBILE_RELEASE_REF_TOKEN: "write-token",
    });
    expect(conflict.status).toBe(1);
    expect(conflict.stderr).toContain("already points at a different commit");
  });

  it("recovers from newer trusted main with pinned original tooling and rejects recovery-time drift", () => {
    const fixture = createFixture();
    const outputs = authorize(fixture);
    signIntentFile(fixture, outputs);
    git(fixture.source, "checkout", "-b", "trusted-main-after-upload", fixture.baseSha);
    git(fixture.source, "commit", "--allow-empty", "-m", "advance trusted main after upload");
    const recoveryWorkflowSha = git(fixture.source, "rev-parse", "HEAD");
    git(fixture.trusted, "fetch", "origin", recoveryWorkflowSha);
    git(fixture.trusted, "checkout", "--detach", recoveryWorkflowSha);
    resetState(fixture);
    const recovery = {
      ...recordOverrides(fixture, outputs),
      GH_ORIGINAL_CONCLUSION: '"failure"',
      GH_ORIGINAL_STATUS: "completed",
      GH_MAIN_REFS: `${recoveryWorkflowSha},${recoveryWorkflowSha}`,
      GITHUB_RUN_ID: "999",
      GITHUB_SHA: recoveryWorkflowSha,
      MOBILE_RECOVERY: "true",
      MOBILE_WORKFLOW_SHA: recoveryWorkflowSha,
    };
    const validation = runAuthority(fixture, "validate-record", recovery);
    expect(validation.status, validation.stderr).toBe(0);
    expect(fs.readFileSync(fixture.ghLog, "utf8")).toContain(
      `"--source-digest","${fixture.baseSha}"`,
    );

    resetState(fixture);
    const staleMain = runAuthority(fixture, "validate-record", {
      ...recovery,
      GH_MAIN_REFS: `${recoveryWorkflowSha},${OTHER_SHA}`,
    });
    expect(staleMain.status).toBe(1);
    expect(staleMain.stderr).toContain("Main changed during initial mobile release authorization");

    resetState(fixture);
    const successful = runAuthority(fixture, "validate-record", {
      ...recovery,
      GH_ORIGINAL_CONCLUSION: '"success"',
    });
    expect(successful.status).toBe(1);
    expect(successful.stderr).toContain("run identity is not exact");
  });

  it("mints write authority only after validation and invokes only trusted recorder code", () => {
    const source = fs.readFileSync(".github/actions/mobile-release-authority/action.yml", "utf8");
    const action = parse(source) as {
      runs: {
        steps: Array<{
          "continue-on-error"?: unknown;
          env?: Record<string, string>;
          if?: unknown;
          name: string;
          run?: string;
          uses?: string;
          with?: Record<string, unknown>;
        }>;
      };
    };
    const validateIndex = action.runs.steps.findIndex(
      (step) => step.name === "Validate immutable release ref intent",
    );
    const tokenIndex = action.runs.steps.findIndex(
      (step) => step.name === "Create mobile release ref token",
    );
    const recordIndex = action.runs.steps.findIndex(
      (step) => step.name === "Record immutable mobile release ref",
    );

    expect(tokenIndex).toBe(validateIndex + 1);
    expect(recordIndex).toBe(tokenIndex + 1);
    for (const stepIndex of [validateIndex, tokenIndex, recordIndex]) {
      expect(action.runs.steps[stepIndex]?.if).toBe("inputs.operation == 'record'");
      expect(action.runs.steps[stepIndex]?.["continue-on-error"]).toBeUndefined();
    }
    expect(action.runs.steps[tokenIndex]?.with).toMatchObject({
      "app-id": "2729701",
      "permission-contents": "write",
      owner: "openclaw",
      repositories: "openclaw",
    });
    expect(action.runs.steps[recordIndex]?.env).toEqual({
      GH_TOKEN: "${{ github.token }}",
      MOBILE_RELEASE_REF_TOKEN: "${{ steps.mobile-release-ref-token.outputs.token }}",
    });
    expect(action.runs.steps[recordIndex]?.run).toBe(
      'node --experimental-strip-types "$MOBILE_ACTION_PATH/authority.mjs" record',
    );
    expect(source).not.toContain("pnpm ");
    expect(source).not.toContain("Fastfile");
    expect(source).not.toContain("extraheader");
  });

  it("keeps upload and recovery credentials inside one protected platform boundary", () => {
    const workflows = [
      {
        environment: "ios-beta-release",
        file: ".github/workflows/ios-beta-release.yml",
        name: "iOS Beta Release",
        platform: "ios",
        signingCheckoutName: "Checkout encrypted iOS signing assets",
        signingCheckoutRevalidateName:
          "Revalidate release authority immediately before iOS signing checkout",
        signingMaterializeName: undefined,
        signingMaterializeRevalidateName: undefined,
        setupBeforeSigning: [],
      },
      {
        environment: "android-beta-release",
        file: ".github/workflows/android-beta-release.yml",
        name: "Android Beta Release",
        platform: "android",
        signingCheckoutName: "Checkout encrypted Android signing assets",
        signingCheckoutRevalidateName:
          "Revalidate release authority immediately before Android signing checkout",
        signingMaterializeName: "Materialize Android release signing",
        signingMaterializeRevalidateName:
          "Revalidate release authority immediately before Android signing materialization",
        setupBeforeSigning: [
          "Setup Node environment",
          "Setup Android toolchain",
          "Setup Ruby",
          "Install locked Fastlane bundle",
        ],
      },
    ] as const;

    for (const {
      environment,
      file,
      name,
      platform,
      signingCheckoutName,
      signingCheckoutRevalidateName,
      signingMaterializeName,
      signingMaterializeRevalidateName,
      setupBeforeSigning,
    } of workflows) {
      const source = fs.readFileSync(file, "utf8");
      const workflow = parse(source) as {
        jobs: Record<
          string,
          {
            environment?: string;
            if?: unknown;
            needs?: string;
            steps: Array<{
              "continue-on-error"?: unknown;
              env?: Record<string, string>;
              if?: unknown;
              name: string;
              run?: string;
              uses?: string;
              with?: Record<string, unknown>;
            }>;
          }
        >;
        name: string;
        on: Record<string, unknown>;
      };
      expect(workflow.name).toBe(name);
      expect(Object.keys(workflow.on)).toEqual(["workflow_dispatch"]);
      expect(Object.keys(workflow.jobs)).toEqual(["authorize", "release", "recover-record"]);
      expect(workflow.jobs.authorize?.environment).toBeUndefined();
      expect(workflow.jobs.release?.environment).toBe(environment);
      expect(workflow.jobs["recover-record"]?.environment).toBe(environment);
      const authorityCheckouts = Object.values(workflow.jobs).flatMap((job) =>
        job.steps.filter(
          (step) =>
            typeof step.with?.["sparse-checkout"] === "string" &&
            step.with["sparse-checkout"].includes(".github/actions/mobile-release-authority"),
        ),
      );
      expect(authorityCheckouts).toHaveLength(5);
      for (const checkout of authorityCheckouts) {
        expect(checkout.uses, `${file}:${checkout.name}:uses`).toMatch(/^actions\/checkout@/u);
        expect(checkout.with?.["fetch-depth"], `${file}:${checkout.name}:fetch-depth`).toBe(0);
      }

      for (const [jobName, job] of Object.entries(workflow.jobs)) {
        if (JSON.stringify(job).includes("GH_APP_PRIVATE_KEY")) {
          expect(job.environment, `${file}:${jobName}`).toBe(environment);
        }
      }

      const release = workflow.jobs.release;
      if (!release) {
        throw new Error(`${file}: missing release job`);
      }
      expect(release.needs).toBe("authorize");
      expect(release.if).toBe(
        "inputs.operation == 'upload-and-record' && needs.authorize.outputs.approved == 'true'",
      );
      const signingRevalidateIndex = release.steps.findIndex(
        (step) => step.name === "Revalidate release authority immediately before signing access",
      );
      const signingTokenIndex = release.steps.findIndex(
        (step) => step.name === "Create apps-signing read token",
      );
      const signingCheckoutIndex = release.steps.findIndex(
        (step) => step.name === signingCheckoutName,
      );
      const signingCheckoutRevalidateIndex = release.steps.findIndex(
        (step) => step.name === signingCheckoutRevalidateName,
      );
      expect(signingRevalidateIndex).toBeGreaterThan(-1);
      expect(signingTokenIndex).toBe(signingRevalidateIndex + 1);
      expect(signingCheckoutRevalidateIndex).toBe(signingTokenIndex + 1);
      expect(signingCheckoutIndex).toBe(signingCheckoutRevalidateIndex + 1);
      for (const setupName of setupBeforeSigning) {
        expect(
          release.steps.findIndex((step) => step.name === setupName),
          `${file}:${setupName}`,
        ).toBeLessThan(signingRevalidateIndex);
      }

      const signingBoundaryIndexes = [
        signingRevalidateIndex,
        signingTokenIndex,
        signingCheckoutRevalidateIndex,
        signingCheckoutIndex,
      ];
      const signingAuthorityIndexes = [signingRevalidateIndex, signingCheckoutRevalidateIndex];
      if (signingMaterializeName) {
        const signingMaterializeRevalidateIndex = release.steps.findIndex(
          (step) => step.name === signingMaterializeRevalidateName,
        );
        const signingMaterializeIndex = release.steps.findIndex(
          (step) => step.name === signingMaterializeName,
        );
        expect(signingMaterializeRevalidateIndex).toBe(signingCheckoutIndex + 1);
        expect(signingMaterializeIndex).toBe(signingMaterializeRevalidateIndex + 1);
        signingBoundaryIndexes.push(signingMaterializeRevalidateIndex, signingMaterializeIndex);
        signingAuthorityIndexes.push(signingMaterializeRevalidateIndex);
      }
      for (const stepIndex of signingAuthorityIndexes) {
        expect(release.steps[stepIndex]?.uses, `${file}:${stepIndex}:uses`).toBe(
          "./.mobile-release-authority/.github/actions/mobile-release-authority",
        );
        expect(release.steps[stepIndex]?.with, `${file}:${stepIndex}:with`).toEqual({
          "authority-run-id": "${{ needs.authorize.outputs.run_id }}",
          operation: "revalidate",
          platform,
          "target-ref": "${{ needs.authorize.outputs.target_ref }}",
          "target-sha": "${{ env.RELEASE_TARGET_SHA }}",
          "workflow-full-ref": "${{ github.workflow_ref }}",
          "workflow-path": file,
          "workflow-sha": "${{ github.workflow_sha }}",
        });
      }
      for (const stepIndex of signingBoundaryIndexes) {
        expect(release.steps[stepIndex]?.if, `${file}:${stepIndex}:if`).toBeUndefined();
        expect(
          release.steps[stepIndex]?.["continue-on-error"],
          `${file}:${stepIndex}:continue-on-error`,
        ).toBeUndefined();
      }

      const revalidateIndex = release.steps.findIndex(
        (step) => step.name === "Revalidate release authority immediately before upload",
      );
      const uploadIndex = release.steps.findIndex((step) => step.name.startsWith("Upload "));
      const intentIndex = release.steps.findIndex((step) => step.name.startsWith("Upload exact "));
      const recorderIndex = release.steps.findIndex(
        (step) => step.name === "Checkout trusted mobile release recorder",
      );
      const recordIndex = release.steps.findIndex((step) =>
        step.name.startsWith("Validate and record immutable"),
      );
      expect(revalidateIndex).toBeGreaterThan(-1);
      expect(uploadIndex).toBe(revalidateIndex + 1);
      expect(intentIndex).toBeGreaterThan(uploadIndex);
      expect(recorderIndex).toBeGreaterThan(intentIndex);
      expect(recordIndex).toBeGreaterThan(recorderIndex);
      expect(release.steps[revalidateIndex]?.if).toBeUndefined();
      expect(release.steps[revalidateIndex]?.["continue-on-error"]).toBeUndefined();
      expect(release.steps[uploadIndex]?.if).toBeUndefined();
      expect(release.steps[uploadIndex]?.["continue-on-error"]).toBeUndefined();
      const intentPath = `\${{ runner.temp }}/mobile-release-intent-${platform}/intent.json`;
      const runnerIntentPath = intentPath.replace("${{ runner.temp }}", "$RUNNER_TEMP");
      const uploadCommands =
        release.steps[uploadIndex]?.run?.split("\n").map((line) => line.trim()) ?? [];
      expect(release.steps[uploadIndex]?.env?.OPENCLAW_MOBILE_RELEASE_INTENT_PATH).toBe(intentPath);
      expect(uploadCommands).toContain(`test "$(wc -c < "${runnerIntentPath}")" -le 4096`);
      expect(release.steps[intentIndex]?.with).toMatchObject({
        path: intentPath,
        "retention-days": 30,
      });
      expect(release.steps[uploadIndex]?.env).not.toHaveProperty("GH_APP_PRIVATE_KEY");
      expect(release.steps[uploadIndex]?.env).not.toHaveProperty("MOBILE_RELEASE_REF_TOKEN");
      expect(release.steps[recordIndex]?.with?.operation).toBe("record");

      if (platform === "android") {
        const rubyStep = release.steps.find((step) => step.name === "Setup Ruby");
        const bundleStep = release.steps.find(
          (step) => step.name === "Install locked Fastlane bundle",
        );
        expect(rubyStep?.with).toMatchObject({
          "bundler-cache": false,
          "ruby-version": "3.4.10",
          "working-directory": "apps/android",
          bundler: "2.6.9",
        });
        expect(bundleStep?.run).toContain("bundle _2.6.9_ install --jobs 4 --retry 3");
        expect(bundleStep?.run).toContain("bundle _2.6.9_ check");
        expect(bundleStep?.run).toContain("bundle _2.6.9_ exec ruby");
        expect(source).not.toContain("gem install fastlane");
      }

      const secretPlacements = Object.entries(workflow.jobs).flatMap(([jobName, job]) =>
        job.steps.flatMap((step) => {
          const serialized = JSON.stringify(step);
          return ["GH_APP_PRIVATE_KEY", "MATCH_PASSWORD"]
            .filter((secret) => serialized.includes(`secrets.${secret}`))
            .map((secret) => ({ jobName, secret, stepName: step.name }));
        }),
      );
      expect(secretPlacements).toEqual(
        platform === "ios"
          ? [
              {
                jobName: "release",
                secret: "GH_APP_PRIVATE_KEY",
                stepName: "Create apps-signing read token",
              },
              {
                jobName: "release",
                secret: "MATCH_PASSWORD",
                stepName: "Upload and distribute iOS beta",
              },
              {
                jobName: "release",
                secret: "GH_APP_PRIVATE_KEY",
                stepName: "Validate and record immutable iOS release ref",
              },
              {
                jobName: "recover-record",
                secret: "GH_APP_PRIVATE_KEY",
                stepName: "Validate and recover immutable iOS release ref",
              },
            ]
          : [
              {
                jobName: "release",
                secret: "GH_APP_PRIVATE_KEY",
                stepName: "Create apps-signing read token",
              },
              {
                jobName: "release",
                secret: "MATCH_PASSWORD",
                stepName: "Materialize Android release signing",
              },
              {
                jobName: "release",
                secret: "GH_APP_PRIVATE_KEY",
                stepName: "Validate and record immutable Android release ref",
              },
              {
                jobName: "recover-record",
                secret: "GH_APP_PRIVATE_KEY",
                stepName: "Validate and recover immutable Android release ref",
              },
            ],
      );

      const recoveryJob = workflow.jobs["recover-record"];
      if (!recoveryJob) {
        throw new Error(`${file}: missing recover-record job`);
      }
      const recovery = JSON.stringify(recoveryJob);
      const recoveryCommands = recoveryJob.steps.map((step) => step.run ?? "").join("\n");
      expect(recovery).not.toContain("Checkout approved release target");
      expect(recovery).not.toContain("apps-signing");
      expect(recoveryCommands).not.toContain("pnpm ");
      expect(recoveryCommands).not.toContain("fastlane");
      expect(recovery).toContain('"recovery":"true"');
      expect(source).not.toContain("workflow_run");
      expect(source).not.toContain("secrets.MOBILE_RELEASE_REF_TOKEN");
      expect(source).toContain("release/YYYY.M.PATCH-mobile");
    }
  });

  it("passes the protected TestFlight group variable only to the iOS upload step", () => {
    const source = fs.readFileSync(".github/workflows/ios-beta-release.yml", "utf8");
    const workflow = parse(source) as {
      jobs: Record<
        string,
        {
          environment?: string;
          steps: Array<{
            env?: Record<string, string>;
            name: string;
            run?: string;
          }>;
        }
      >;
    };
    const placements = Object.entries(workflow.jobs).flatMap(([jobName, job]) =>
      job.steps.flatMap((step) =>
        Object.entries(step.env ?? {})
          .filter(([, value]) => value.includes("TESTFLIGHT_INTERNAL_GROUP"))
          .map(([envName, value]) => ({
            envName,
            jobName,
            runsUpload: step.run?.includes("pnpm ios:release:upload") ?? false,
            value,
          })),
      ),
    );

    expect(source).not.toContain("secrets.TESTFLIGHT_INTERNAL_GROUP");
    expect(source.match(/\$\{\{ vars\.TESTFLIGHT_INTERNAL_GROUP \}\}/gu)).toHaveLength(1);
    expect(workflow.jobs.release?.environment).toBe("ios-beta-release");
    expect(placements).toEqual([
      {
        envName: "TESTFLIGHT_INTERNAL_GROUP",
        jobName: "release",
        runsUpload: true,
        value: "${{ vars.TESTFLIGHT_INTERNAL_GROUP }}",
      },
    ]);
  });
});
