/** Interpreter and runtime option tables used by mutable operand detection. */

export const BUN_SUBCOMMANDS = new Set([
  "add",
  "audit",
  "completions",
  "create",
  "exec",
  "help",
  "init",
  "install",
  "link",
  "outdated",
  "patch",
  "pm",
  "publish",
  "remove",
  "repl",
  "run",
  "test",
  "unlink",
  "update",
  "upgrade",
  "x",
]);

export const BUN_OPTIONS_WITH_VALUE = new Set([
  "--backend",
  "--bunfig",
  "--conditions",
  "--config",
  "--console-depth",
  "--cwd",
  "--define",
  "--elide-lines",
  "--env-file",
  "--extension-order",
  "--filter",
  "--hot",
  "--inspect",
  "--inspect-brk",
  "--inspect-wait",
  "--install",
  "--jsx-factory",
  "--jsx-fragment",
  "--jsx-import-source",
  "--loader",
  "--origin",
  "--port",
  "--preload",
  "--smol",
  "--tsconfig-override",
  "-c",
  "-e",
  "-p",
  "-r",
]);

export const BUN_UNBINDABLE_APPROVAL_OPTIONS = new Set([
  "--bunfig",
  "--config",
  "--cwd",
  "--env-file",
  "--loader",
  "--preload",
  "--tsconfig-override",
  "-r",
]);

export const DENO_RUN_OPTIONS_WITH_VALUE = new Set([
  "--cached-only",
  "--cert",
  "--config",
  "--env-file",
  "--ext",
  "--harmony-import-attributes",
  "--import-map",
  "--inspect",
  "--inspect-brk",
  "--inspect-wait",
  "--location",
  "--log-level",
  "--lock",
  "--node-modules-dir",
  "--no-check",
  "--preload",
  "--reload",
  "--seed",
  "--strace-ops",
  "--unstable-bare-node-builtins",
  "--v8-flags",
  "--watch",
  "--watch-exclude",
  "-L",
]);

export const DENO_UNBINDABLE_APPROVAL_OPTIONS = new Set([
  "--config",
  "--env-file",
  "--import-map",
  "--lock",
  "--node-modules-dir",
  "--preload",
]);

export const NODE_OPTIONS_WITH_FILE_VALUE = new Set([
  "--env-file",
  "--env-file-if-exists",
  "-r",
  "--experimental-loader",
  "--import",
  "--loader",
  "--require",
]);

export const RUBY_UNSAFE_APPROVAL_FLAGS = new Set(["-I", "-r", "--require"]);
export const PERL_UNSAFE_APPROVAL_FLAGS = new Set(["-I", "-M", "-m"]);
